<div class="container">
	<div class="span-11">
		<br>
		<div class="span-9 prepend-2 last">
			<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/logo-lgs-black.png" /></p>
		</div>
		<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/left-bar-1.png" /></p>
	</div>
	<div class="span-26 last" style="background: #fff;">
		<div class="span-18" style="background: #fff;">
			<div class="box" style="background: #fff;">
				<h3>LGS Legal Database</h3>
				This is the most important content of LGS Online. LGS Legal Database consists of LGS database compiled for more than 25 years of corporate law practices in Indonesia.
				<hr>
				<h3>News & Opportunities</h3>
				<p>Lorem ipsum dolor sit amet, <em>consectetuer adipiscing elit</em>. Nunc congue ipsum vestibulum libero. Aenean vitae justo. Nam eget tellus. Etiam convallis, est eu lobortis mattis, lectus tellus tempus felis, a ultricies erat ipsum at metus.</p>
				<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. <a href="#">Morbi et risus</a>. Aliquam nisl. Nulla facilisi. Cras accumsan vestibulum ante. Vestibulum sed tortor. Praesent <span class="caps">SMALL CAPS</span> tempus fringilla elit. Ut elit diam, sagittis in, nonummy in, gravida non, nunc. Ut orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam egestas, orci eu imperdiet malesuada, nisl purus fringilla odio, quis commodo est orci vitae justo. Aliquam placerat odio tincidunt nulla. Cras in libero. Aenean rutrum, magna non tristique posuere, erat odio eleifend nisl, non convallis est tortor blandit ligula. Nulla id augue.</p>
			</div>
		</div>
		<div class="span-8 last" style="background: ;">
			<div class="boxSideBar" style="background: #fff;">
				<h3>About LGS Online</h3>
				<IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/right-side-icon.png" />
				<p>This is the most important content of LGS Online. LGS Legal Database consists of LGS database compiled for more than 25 years.</p>
				<hr class="space">
				<h3>About LGS Online</h3>
				<IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/right-side-icon.png" />
				<p>This is the most important content of LGS Online. LGS Legal Database consists of LGS database compiled for more than 25 years.</p>
				<hr class="space">
				<h3>About LGS Online</h3>
				<IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/right-side-icon.png" />
				<p>This is the most important content of LGS Online. LGS Legal Database consists of LGS database compiled for more than 25 years.</p>
			</div>
		</div>
	</div>
</div>

<div class="span-18 prepend-19 last">
	<br>
	<h2 class="alt">Changes the Way Legal Services are Provided in Indonesia</h2>
	<hr>
</div>