<div class="span-24 last" style="background:#fff;">
	<div class="span-13 colborder" style="background:#fff;">
		<div class="span-13 colborder" style="background:#f7f7f7;">
			<IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/head4.jpg" />
				<div class="span-12 prepend-1 last">
					<hr class="space">
					<h3>Welcome</h3>
					<p>Lorem ipsum dolor sit amet, <em>consectetuer adipiscing elit</em>. Nunc congue ipsum vestibulum libero. Aenean vitae justo. Nam eget tellus. Etiam convallis, est eu lobortis mattis, lectus tellus tempus felis, a ultricies erat ipsum at metus.</p>
				</div>
				<div class="span-5 prepend-1 colborder">
					<h3>Our Team</h3>
					<p>Lorem ipsum dolor sit amet, <em>consectetuer adipiscing elit</em>. Nunc congue ipsum vestibulum libero. Aenean vitae justo. Nam eget tellus. Etiam convallis, est eu lobortis mattis, lectus tellus tempus felis, a ultricies erat ipsum at metus.</p>
				</div>
				<div class="span-6 last">
					<h3>Firm & Services</h3>
					<p>Lorem ipsum dolor sit amet, <em>consectetuer adipiscing elit</em>. Nunc congue ipsum vestibulum libero. Aenean vitae justo. Nam eget tellus. Etiam convallis, est eu lobortis mattis, lectus tellus tempus felis, a ultricies erat ipsum at metus.</p>
				</div>
			</div>
			<div class="span-12 prepend-1 colborder last" style="background:;">
				<hr class="space">
				<h3>Message from the Board</h3>
				This is the most important content of LGS Online. LGS Legal Database consists of LGS database compiled for more than 25 years of corporate law practices in Indonesia.
				<br><br>
				<p><a href="<?echo KUTU_ROOT_URL;?>/identity/login">Sign up or login</a> to get access to the database.</p>
			</div>
	</div>
	<div class="span-10 last" style="background:#FFF;">
		<hr class="space">
		<h3>LGS Legal Database</h3>
		This is the most important content of LGS Online. LGS Legal Database consists of LGS database compiled for more than 25 years of corporate law practices in Indonesia.
		<br><br>
		<p><a href="<?echo KUTU_ROOT_URL;?>/identity/login">Sign up or login</a> to get access to the database.</p>
		
		<h3>News & Opportunities</h3>
		<p>Lorem ipsum dolor sit amet, <em>consectetuer adipiscing elit</em>. Nunc congue ipsum vestibulum libero. Aenean vitae justo. Nam eget tellus. Etiam convallis, est eu lobortis mattis, lectus tellus tempus felis, a ultricies erat ipsum at metus.</p>
		<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. <a href="#">Morbi et risus</a>. Aliquam nisl. Nulla facilisi. Cras accumsan vestibulum ante. Vestibulum sed tortor. Praesent <span class="caps">SMALL CAPS</span> tempus fringilla elit. Ut elit diam, sagittis in, nonummy in, gravida non, nunc. Ut orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam egestas, orci eu imperdiet malesuada, nisl purus fringilla odio, quis commodo est orci vitae justo. Aliquam placerat odio tincidunt nulla. Cras in libero. Aenean rutrum, magna non tristique posuere, erat odio eleifend nisl, non convallis est tortor blandit ligula. Nulla id augue.</p>
	
		<h3>Contact Address</h3>
		
		<p>
			Menara Imperium 30th Floor
			<br> 
			Jl. H. R. Rasuna Said Kav. 1 Kuningan, 
			<br>
			Jakarta 12980, Indonesia. 
			<div style="padding-top:0px"></div>
			Telephone : (62-21) 831 5005, 831 5025 
			<br>
			Fax : (62-21) 831 5015, 831 5025 
			<div style="padding-top:10px"></div>
			Email :
			<br>
			lubis@lgslaw.co.id
			<br>
			ganie@lgslaw.co.id
			<br>
			surowidjojo@lgslaw.co.id
			<hr class="space">
		</p>
	</div>
</div>
<div class="span-5 colborder">
	
</div>

<div class="span-5 last">
	
</div>


<hr>
<h2 class="alt">You may pick and choose amongst these and many more features, so be bold.</h2>
<hr>