<br>
<div class="span-24 prepend-2 colborder">
	<?echo $this->action('breadcrumbs','pages_component','site',array('node'=>$this->folderGuid));?>
	<h2 class="alt"><?echo $this->folderTitle;?></h2>
	<hr>
	<h3><?echo Kutu_Core_Util::getCatalogAttributeValue($this->catalogGuid, 'fixedTitle')?></h3>
	<h3><?echo Kutu_Core_Util::getCatalogAttributeValue($this->catalogGuid, 'fixedSubTitle')?></h3>
	<h4 class="alt"><?echo $this->row->modifiedDate?></h4>
	<?echo Kutu_Core_Util::getCatalogAttributeValue($this->catalogGuid, 'fixedContent')?>
	<br>&nbsp;
	<?echo $this->action('document','pages_component','site',array("g"=>$this->catalogGuid));?>
</div>
<div class="span-9 append-1 last">
	<?//echo $this->widget1->render();?>
	
	<?=$this->render('lgsolrightmenu.phtml')?>
</div>
