<div style="background:#343434">
	<div class="container">
		<div class="span-11">
			<div style="text-align:left;margin:0.5em 0 0.2em 0;">
				<IMG src="<?echo KUTU_ROOT_URL;?>/common/images/logo-iso2.jpg" />
			</div>
		</div>
		<div class="span-26 last">
			<div style="text-align:right;margin:1.0em 0 0.5em 0;">
				<span style="color:#fff;">LGS Online. Copyright 2009. All Rights Reserved.</span>
			</div>
		</div>
	<div>
		
</div>