<div class="container">
	<div class="span-18" style="margin:0.8em 0 0.5em 0;">
		<IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/logo-lgs-top.png" />
	</div>
	<div class="span 19 last" style="text-align:right;margin:0.8em 0 0.8em 0;">
		<div class=""><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/logo-lgsol-top.png" /></div>
	</div>
</div>

<div class="darker"></div>
<div style="background:#fd9a01">
	<div class="container">
		<!--<div class="darker"></div>-->
	
			<div class="span-37 last" style="background: ;">
					<?echo $this->action('mainmenu','component','site')?>
			</div>
		</div>
	</div>
</div>
<div class="darker">
	
</div>
<div class="container">
	<div class="span-37 last" style="background: #000">
		<IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/header.png" />
	</div>
</div>
<div style="background:#343434">
	<div class="container">
		<!--<div class="darker"></div>-->
	
			<div class="span-26" style="background: ;">
				<div style="text-align:right;margin:0.9em 0 0.8em 0;">
				<?if(empty($this->username)){?>
						<a href="<?echo KUTU_ROOT_URL;?>/identity/login"><span style="color:#fff;">Login/Sign up</span></a> <span style="color:#fff;">|</span>
					<?}
					else { echo "<span style='color:#fff;'>Hello <strong>". $this->username."</strong>, </span>";?>
						 <a href="<?echo KUTU_ROOT_URL;?>/identity/logout"><span style="color:#fff;">Logout</span></a> <span style="color:#fff;">|</span>
						<a href="<?echo KUTU_ROOT_URL;?>/site/myaccount"><span style="color:#fff;">My Account</span></a> <span style="color:#fff;">|</span>
						<a href="<?echo KUTU_ROOT_URL;?>/site/store/checkout"><span style="color:#fff;">View Cart</span></a> <span style="color:#fff;">|</span>
					<?}?>
					<a href="#"><span style="color:#fff;">Help</span></a><span style="color:#fff;"> | </span><a href="#"><span style="color:#fff;">Advanced Search</span></a> 
				</div>
			</div>
			<div class="span-11 last">
				<div style="text-align:right;margin:0.6em 0 0.8em 0;">
				<form id="frmSearch" name="frmSearch" action="<?echo KUTU_ROOT_URL;?>/site/dms/search" method="GET">
					<input id="sQuery" name="sQuery" size=30 value='<?echo $this->sQuery;?>'>
					<input type="hidden" id="sLimit" name="sLimit" value="10">
					<input type="hidden" id="sOffset" name="sOffset" value="<?echo $this->sOffset;?>">
					<input type="submit" id="btnGoSearch" value="Search">
				</form>
				</div>
			</div>
		</div>
	</div>
</div>