<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;">
	<title><?echo $this->pageTitle;?></title>

  <!-- Framework CSS -->
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/screen.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/print.css" type="text/css" media="print">
  <!--[if IE]><link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->

	
	<!-- Import fancy-type plugin for the sample page. -->
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/plugins/fancy-type/screen.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/modules/site/styles/site.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/modules/site/styles/superfish.css" type="text/css" media="screen, projection">

	<!--[if IE]><script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/js/excanvas.js"></script><![endif]-->
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.roundcorners.2.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/splitter.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.cookie.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.flickrmenu.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.validate.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/superfish.js"></script>
	
	<script type="text/javascript">
		$(document).ready(function(){
			
		});
	</script>
	<script type="text/javascript">
		$(document).ready(function(){
			 $('ul.sf-menu').superfish();


		});
	</script>

</head>
<?php //flush(); ?>
<body style="background:#E8E8E8;">
	<div class="container">
		<hr class="space">
		<div class="span-10 prepend-14 last">
			<p><?if(empty($this->username)){?>
					<a href="<?echo KUTU_ROOT_URL;?>/identity/login">Login/Sign up</a> |
				<?}
				else { echo "Hello, ". $this->username;?>
					 <a href="<?echo KUTU_ROOT_URL;?>/identity/logout">Logout</a> |
					<a href="<?echo KUTU_ROOT_URL;?>/site/myaccount">My Account</a> |
					<a href="<?echo KUTU_ROOT_URL;?>/site/store/checkout">View Cart</a> |
				<?}?>
				<a href="#">Help</a> | <a href="#">Contact Us</a></p>
		</div>
		<hr>
		<div class="span-24 last">
			<div class="span-5 colborder">
			  <!--<h1>LGS Online</h1>-->
				<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/images/logo-lgs.gif" /></p>
			</div>

			<div class="span-8">
			  <h6>Changes dramatically the way legal services are provided in Indonesia</h6>

			</div>

			<div class="span-10 last">
				<div class="span-2">
					<span style="font-size:14px">&nbsp;</span>
				</div>
				<div class="span-8 last">
					<form id="frmSearch" name="frmSearch" action="<?echo KUTU_ROOT_URL;?>/site/dms/search" method="GET">
						<input id="sQuery" name="sQuery" size=30 value='<?echo $this->sQuery;?>'>
						<input type="hidden" id="sLimit" name="sLimit" value="10">
						<input type="hidden" id="sOffset" name="sOffset" value="<?echo $this->sOffset;?>">
						<input type="submit" id="btnGoSearch" value="Search">
					</form>
				</div>
			</div>
		</div>
		
		<div class="darker"></div>
		<div class="span-24" style="background: ">
				<?echo $this->action('mainmenu','component','site')?>
		</div>
		<div class="lighter"></div>
		
		
		

		<?php echo $this->layout()->content; ?>
		
		<div class="span-3 prepend-21 last"><IMG src="<?echo KUTU_ROOT_URL;?>/common/images/logo-iso2.jpg" /></div>	
	</div>
</body>
</html>