<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Sample Page</title>

  <!-- Framework CSS -->
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/screen.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/print.css" type="text/css" media="print">
  <!--[if IE]><link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->

	
	<!-- Import fancy-type plugin for the sample page. -->
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/plugins/fancy-type/screen.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/fb.css" type="text/css" media="screen, projection">

	<!--[if IE]><script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/js/excanvas.js"></script><![endif]-->
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.roundcorners.2.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/splitter.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.cookie.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.flickrmenu.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.validate.js"></script>
	
	<script type="text/javascript">
		$(document).ready(function(){
			
		});
	</script>

</head>

<body>
	<div class="container">
		<hr class="space">
		<div class="span-5 colborder">
		  <!--<h1>LGS Online</h1>-->
			<IMG src="<?echo KUTU_ROOT_URL;?>/common/images/logo-lgs.gif" />
		</div>

		<div class="span-10">
		  <h6>Get more from Us</h6>

		  <p><a href="<?echo KUTU_ROOT_URL;?>/site">Home</a> |
			<?if(empty($this->username)){?> 
				<a href="<?echo KUTU_ROOT_URL;?>/site/index/about">Lgs Legal Database</a> 
			<?}
			else { //echo "Hello, ". $this->username;?>
				 <a href="<?echo KUTU_ROOT_URL;?>/dms">Lgs Legal Database</a>
			<?}?>
			| <a href="#">News</a> | <a href="#">LGS Profile</a></p>
		</div>
		
		<div class="span-8 last">
		  <!--<h6>Don't Have an Account Still?</h6>-->
		  <p>
			<?if(empty($this->username)){?>
				<a href="<?echo KUTU_ROOT_URL;?>/identity/login">Login/Sign up</a> |
			<?}
			else { echo "Hello, ". $this->username;?>
				 <a href="<?echo KUTU_ROOT_URL;?>/identity/logout">Logout</a> |
				<a href="<?echo KUTU_ROOT_URL;?>/site/myaccount">My Account</a> |
				<a href="<?echo KUTU_ROOT_URL;?>/site/store/checkout">View Cart</a> |
			<?}?>
			<a href="#">Help</a> | <a href="#">Contact Us</a></p>
		</div>  
		
		<hr>
		<div class="span-2 prepend-14">
			<span style="font-size:16px">Search</span>
		</div>
		<div class="span-8 last">
			<form id="frmSearch" name="frmSearch" action="<?echo KUTU_ROOT_URL;?>/site/dms/search" method="GET">
				<input id="sQuery" name="sQuery" size=30 value='<?echo $this->sQuery;?>'>
				<input type="hidden" id="sLimit" name="sLimit" value="10">
				<input type="hidden" id="sOffset" name="sOffset" value="<?echo $this->sOffset;?>">
				<input type="submit" id="btnGoSearch" value="Go">
			</form>
		</div>
		&nbsp;
		<hr>
		<?php echo $this->layout()->content; ?>
		
		<div class="span-3 prepend-21"><IMG src="<?echo KUTU_ROOT_URL;?>/common/images/logo-iso2.jpg" /></div>	
	</div>
</body>
</html>