<div class="span-2">
	<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/aboutlgs_s.jpg" /></p>
</div>
<div class="span-9 last">
	<p class="leftMenu"><strong><a href="<?= KUTU_ROOT_URL;?>/pages/g/lgs4a1d79ad94802" style="color:#fff">About LGS</a></strong>
		<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc congue ipsum libero. 
	</p>
</div>
<div class="span-2 clear">
	<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgsfirm.jpg" /></p>
</div>
<div class="span-9 last">
	<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d7ab79b912" style="color:#fff">LGS Firm & Services</a></strong>
		<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc congue ipsum libero. 
	</p>
</div>
<div class="span-2 clear">
	<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgsexp.jpg" /></p>
</div>
<div class="span-9 last">
	<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a4dc4239a6a7" style="color:#fff">LGS Experience</a></strong>
		<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc congue ipsum libero. 
	</p>
</div>
<div class="span-2 clear">
	<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgspartners.jpg" /></p>
</div>
<div class="span-9 last">
	<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a4dc4e9a29c6" style="color:#fff">LGS Partners</a></strong>
		<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc congue ipsum libero. 
	</p>
</div>
<div class="span-2 clear">
	<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgslawyers.jpg" /></p>
</div>
<div class="span-9 last">
	<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a4dc57987c84" style="color:#fff">LGS Lawyers</a></strong>
		<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc congue ipsum libero. 
	</p>
</div>
<div class="span-2 clear">
	<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgsawards.jpg" /></p>
</div>
<div class="span-9 last">
	<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d8484cd013" style="color:#fff">LGS Awards</a></strong>
		<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc congue ipsum libero. 
	</p>
</div>
<div class="span-2 clear">
	<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgsothersay.jpg" /></p>
</div>
<div class="span-9 last">
	<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d84f8ab672" style="color:#fff">What Others Say About LGS</a></strong>
		<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc congue ipsum libero. 
	</p>
</div>
<div class="span-2 clear">
	<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgsnews.jpg" /></p>
</div>
<div class="span-9 last">
	<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d79809737a" style="color:#fff">LGS News</a></strong>
		<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc congue ipsum libero. 
	</p>
</div>
<div class="span-2 clear">
	<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgsclients.jpg" /></p>
</div>
<div class="span-9 last">
	<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d8494a0b6a" style="color:#fff">LGS Clients</a></strong>
		<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc congue ipsum libero. 
	</p>
</div>