<a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d7b0009192"><h3 class="rightMenu">About LGS Online</h3></a>
<a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d7b0009192"><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_aboutlgsol.jpg" /></a>
<p>This is the most important content of LGS Online. LGS Legal Database consists of LGS database compiled for more than 25 years.
<hr class="space">

<a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d7937a6f9b"><h3 class="rightMenu">Indonesia Under Review</h3></a>
<a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d7937a6f9b"><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_underreview.jpg" /></a>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc congue ipsum libero.
<hr class="space">

<a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d783104616"><h3 class="rightMenu">LGS Online Newsletter</h3></a>
<a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d783104616"><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_newsletter.jpg" /></a>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc congue ipsum libero.
<hr class="space">

<a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d7a02e32c1"><h3 class="rightMenu">Who's Who in Indonesia</h3></a>
<a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d7a02e32c1"><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_who.jpg" /></a>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc congue ipsum libero.
<hr class="space">

<a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d7a32b3755"><h3 class="rightMenu">Important Addresses</h3></a>
<a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d7a32b3755"><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_address.jpg" /></a>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc congue ipsum libero.
<hr class="space">