<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->
<!-- item per page = <?=$this->itemCountPerPage;?>
sort by = <?=$this->sort;?> -->
<?php if ($this->pageCount): ?>
<div class="paginationControl">
	<!-- First page link -->
	        <?php if (isset($this->previous)): ?>
	              <a href="<?= $this->url(array('page' => $this->first)); ?>">First</a> |
	        <?php else: ?>
	                <span class="disabled">First</span> |
	        <?php endif; ?>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
    &lt; Previous
  </a> |
<?php else: ?>
  <span class="disabled">&lt; Previous</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
    Next &gt;
  </a>
<?php else: ?>
  <span class="disabled">Next &gt;</span>
<?php endif; ?>
<!-- Last page link -->
        <?php if (isset($this->next)): ?>
              | <a href="<?= $this->url(array('page' => $this->last)); ?>">Last</a>
        <?php else: ?>
            <span class="disabled">| Last</span>
        <?php endif; ?>
</div>
<?php endif; ?>