<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/modules/admin/styles/user.css" type="text/css">
</script>
<script type="text/javascript">
	$(document).ready(function(){
		$('#menu').flickrmenu();
	});
</script>
<br>
<strong>User Management</strong>
<br>&nbsp;
<table width='100%' cellpadding="0" cellspacing="0">
	<tr valign="top">
		<td width="100%" class="" style="padding-left:0px;border-bottom:1px solid #E5E5E5;">
			<div id="menu" >
				  <ul>
					<li>
				      <span class="head_menu">
				        <a href="<?echo KUTU_ROOT_URL;?>/admin/user/browse">Show All Users</a>
				      </span>
				    </li>
				  </ul>
				</div>
			
		</td>
	</tr>
</table>
<table width='100%' cellpadding="0" cellspacing="0" bgcolor="#F7F7F7">
	<tr valign="top">
		<td height="30" bgcolor="" class="">
			<div style="padding-top:10px;padding-left:10px;"></div>
			User data is successfully saved.
			
		</td>
	</tr>
</table>