<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/modules/admin/styles/user.css" type="text/css">

<script type="text/javascript">
	$(document).ready(function(){
		$('#menu').flickrmenu();
		
		$("#lkAssignGroup").click(function(){ 
			assignGroup();
		});
		$("#lkDeleteUser").click(function(){ 
			var aGuid = getCheckedCheckBox("frmUserPager");
			if (confirm("Are you sure you want to delete "+ aGuid.length +' users')) 
			{
				var listGuid = '';
				for (var i = 0; i < aGuid.length; i++){ 
				         listGuid += "/guid/" + aGuid[i] ; 
				      }
				window.location = "<?echo KUTU_ROOT_URL;?>/admin/user/delete"+listGuid;
			}
			
		});
		$("#lkChangePassword").click(function(){ 
			var guid = getOnlyOneCheckBox("frmUserPager");
			//alert(guid);
			if(guid)
				window.location = "<?echo KUTU_ROOT_URL;?>/admin/user/changepassword/guid/"+guid;
		});
		
		function assignGroup()
		{
			var guid = getOnlyOneCheckBox("frmUserPager");
			//alert(guid);
			if(guid)
				window.location = "<?echo KUTU_ROOT_URL;?>/admin/user/assigngroup/guid/"+guid;
		}
		getCheckedCheckBox = function (elementId)
				{
					var content = [];
					var aGuid = new Array();
					var iCount=0;
					$('#' + elementId + ' input').each(function(){
						var el = $(this);
						if ( (el.attr('type').toLowerCase() == 'radio'))
						{
							if ( this.checked )
							{
								content.push([
									'"', el.attr('name'), '": ',
									'value="', ( this.value ), '"',
									( this.disabled ? ', disabled' : '' )
								].join(''));
								aGuid[iCount]=this.value;
								iCount++;
							}
						}
						else
						{
							content.push([
								'"', el.attr('name') + ' '+el.attr('value'), '": ',
								( this.checked ? 'checked' : 'not checked' ), 
								( this.disabled ? ', disabled' : '' )
							].join(''));
							if ( this.checked )
							{
								aGuid[iCount]=el.attr('value');
								iCount++;
							}
						}
						
					});
					return aGuid;
				}
		
		getOnlyOneCheckBox = function (elementId)
				{
					var aGuid = getCheckedCheckBox(elementId);
					
					if(aGuid.length>1)
					{
						alert('You can select ONLY ONE User to edit');
					}
					else
					{	
						if(aGuid.length==0)
							alert('You must select ONE User to edit')
						else
							return aGuid[0];
					}
					return false;
				} 
		
		displayFormOri = function (elementId)
					{
						var content = [];
						$('#' + elementId + ' input').each(function(){
							var el = $(this);
							if ( (el.attr('type').toLowerCase() == 'radio'))
							{
								if ( this.checked )
									content.push([
										'"', el.attr('name'), '": ',
										'value="', ( this.value ), '"',
										( this.disabled ? ', disabled' : '' )
									].join(''));
							}
							else
								content.push([
									'"', el.attr('name') + ' '+el.attr('value'), '": ',
									( this.checked ? 'checked' : 'not checked' ), 
									( this.disabled ? ', disabled' : '' )
								].join(''));
						});
						alert(content.join('\n'));
					}
			displayForm = function (elementId)
					{
						var content = [];
						var aGuid = new Array();
						var iCount=0;
						$('#' + elementId + ' input').each(function(){
							var el = $(this);
							if ( (el.attr('type').toLowerCase() == 'radio'))
							{
								if ( this.checked )
								{
									content.push([
										'"', el.attr('name'), '": ',
										'value="', ( this.value ), '"',
										( this.disabled ? ', disabled' : '' )
									].join(''));
									aGuid[iCount]=this.value;
									iCount++;
								}
							}
							else
							{
								content.push([
									'"', el.attr('name') + ' '+el.attr('value'), '": ',
									( this.checked ? 'checked' : 'not checked' ), 
									( this.disabled ? ', disabled' : '' )
								].join(''));
								if ( this.checked )
								{
									aGuid[iCount]=el.attr('value');
									iCount++;
								}
							}
							
						});
						
						if(aGuid.length>1)
						{
							alert('You can select ONLY ONE User to edit');
						}
						else
						{	
							if(aGuid.length==0)
								alert('You must select ONE User to edit')
							else
								window.location = "<?echo KUTU_ROOT_URL;?>/admin/user/edit/guid/"+aGuid[0];
						}
					}
		
	});
</script>	

<br>
<strong>User Management</strong>
<br>&nbsp;
<table width='100%' cellpadding="0" cellspacing="0">
	<tr valign="top">
		<td width="100%" class="" style="padding-left:0px;border-bottom:1px solid #E5E5E5;">
			<div id="menu" >
				  <ul>
					<li>
				      <span class="head_menu">
				        <a href="#">Select</a>
				        <img src="<?echo KUTU_ROOT_URL;?>/common/images/arrow.png" width="18" height="15" align="top" class="arrow" />
				      </span>
				      <div class="sub_menu">
				        <a href="#">None</a>
				        <a href="#">All</a>
				      </div>
				    </li>
				    <li>
				      <span class="head_menu">
				        <a href="<?echo KUTU_ROOT_URL;?>/admin/user/add">New</a>
				      </span>
				    </li>
					<li>
				      <span class="head_menu">
				        <a href="javascript:void(0);" onclick="displayForm('frmUserPager');return true;">Edit</a>
				      </span>
				    </li>
					<li>
				      <span class="head_menu">
				        <a href="javascript:void(0);" id="lkDeleteUser" name="lkDeleteUser">Delete</a>
				      </span>
				    </li>
				    <li>
				      <span class="head_menu">
				        <a href="#">View</a>
				        <img src="<?echo KUTU_ROOT_URL;?>/common/images/arrow.png" width="18" height="15" align="top" class="arrow" />
				      </span>
				      <div class="sub_menu">
				        <a href="#">All</a>
				        <a href="#">Active</a>
				        <a href="#">Inactive</a>
						<a href="#">Banned</a>
				      </div>
				    </li>
					<li>
				      <span class="head_menu">
				        <a href="#">More</a>
				        <img src="<?echo KUTU_ROOT_URL;?>/common/images/arrow.png" width="18" height="15" align="top" class="arrow" />
				      </span>
				      <div class="sub_menu">
						<a href="javascript:void(0);" id="lkChangePassword" name="lkChangePassword">Change Password</a>
				        <a href="javascript:void(0);" id="lkAssignGroup" name="lkAssignGroup">Assign Group(s)</a>
				        <a href="#">Show Orders</a>
						<a href="#">Delete Users</a>
				      </div>
				    </li>
				  </ul>
				</div>
			
		</td>
	</tr>
	<!--<tr valign="">
		<td width="100%" bgcolor="#F7F7F7" class="tbl_tab_menu" height='30'>New | Edit | Delete</td>
	</tr>-->
</table>
<br>
<form id='frmUserPager'>
<?php echo $this->userPager;?>
</form>
<!--<br>
<table width='100%' cellpadding="0" cellspacing="0" class="tbl1">
	<tr valign="top">
		<td width="250" bgcolor="#F7F7F7" class="tbl1a"><div style="float:right;">test</div></td>
		<td align=right>test2</td>
	</tr>
</table>-->
<br>



