<script type="text/javascript">
$(document).ready(function() {
	$("#commentForm").validate({
		rules: {
			fullname: "required",
			lastname: "required",
			username: {
				required: true,
				minlength: 2,
				remote: "<?php echo KUTU_ROOT_URL;?>/api/user/isusernameavailable/"
			},
			password: {
				required: true,
				minlength: 5
			},
			passwordConfirm: {
				required: true,
				minlength: 5,
				equalTo: "#password"
			},
			email1: {
				required: true,
				email: true,
				remote: "emails.php"
			},
			dateformat: "required",
			terms: "required"
		},
		messages: {
			fullname: "Enter your fullname",
			lastname: "Enter your lastname",
			username: {
				required: "Enter a username",
				minlength: jQuery.format("Enter at least {0} characters"),
				remote: jQuery.format("{0} is already in use")
			},
			password: {
				required: "Provide a password",
				rangelength: jQuery.format("Enter at least {0} characters")
			},
			passwordConfirm: {
				required: "Repeat your password",
				minlength: jQuery.format("Enter at least {0} characters"),
				equalTo: "Enter the same password as above"
			},
			email: {
				required: "Please enter a valid email address",
				minlength: "Please enter a valid email address",
				remote: jQuery.format("{0} is already in use")
			},
			dateformat: "Choose your preferred dateformat",
			terms: " "
		}
		
		
	});
});
</script>
<script type="text/javascript">
	$(document).ready(function(){
		$('#menu').flickrmenu();
	});
</script>
<hr class="space">
<h2 class="alt">User Management: Change Password</h2>
<div id="menu" >
	  <ul>
		<li>
	      <span class="head_menu">
	        <a href="<?echo KUTU_ROOT_URL;?>/admin/user/browse">Show All Users</a>
	      </span>
	    </li>
	  </ul>
	</div>
<hr class="space">
<form class="cmxform" id="commentForm" method="post" action="">
	<fieldset>
		<legend>Login Info</legend>
		<p>
			<label for="username">Username</label>
			<?echo $this->rowUser->username;?>
		</p>
		<p>
			<label for="oldPassword">Old Password</label>
			<input id="oldPassword" name="oldPassword" type="password" class="required" maxlength="50" value="" />
		</p>
		<p>
			<label for="password">New Password</label>
			<input id="password" name="password" type="password" class="required" maxlength="50" value="" />
		</p>
		<p>
			<label for="passwordConfirm">Confirm Password</label>
			<input id="passwordConfirm" name="passwordConfirm" type="password" class="required" maxlength="50" value="" />
		</p>
		<p>
			<input class="submit" type="submit" value="Submit"/>
		</p>
	</fieldset>
</form>