<?php
$bpmMenu = new Kutu_Cms_Bpm_Menu();
?>
<div id="footer-wrap">
	<div id="footer-columns">

		<div class="col3">
			<h3>Our Programs</h3>
			<?
				$rowsetMenu = $bpmMenu->getMenu('nlrp4a35278c49a5c');
				if(count($rowsetMenu)>0) {?>
					<ul>
					<?foreach($rowsetMenu as $row) {?>
						<li>
							<a href="<?echo KUTU_ROOT_URL;?>/pages/g/<?echo $row->guid;?>"><?echo $row->title;?></a>
						</li>
					<?}?>
					</ul>
			<?}?>
		</div>

		<div class="col3-center">&nbsp;</div>
		<!--<div class="col3-center">
			<h3>Sed purus</h3>
			<ul>
				<li><a href="index.html">consequat molestie</a></li>
				<li><a href="index.html">sem justo</a></li>
				<li><a href="index.html">semper</a></li>
				<li><a href="index.html">magna sed purus</a></li>
				<li><a href="index.html">tincidunt</a></li>
			</ul>
		</div>-->

		<div class="col3">
			<h3>Contact Us</h3>
			<ul>
				<li><span style="color:#666666;"><br>
				National Legal Reform Program (NLRP)
				<br>Gedung Setiabudi 2 Lantai 2 Suite 207D
				<br>Jl. H.R. Rasuna Said Kav. 62
				<br>Jakarta 12920
				<br>INDONESIA
				<br>Phone : +62 21 52906813
				<br>Fax : +62 21 52906824
				<br>&nbsp;</span>
				</li>

			</ul>
		</div>

	</div>	

	<div id="footer-bottom">		
		
		<p>
		&copy; 2009 <strong>NLRP - National Legal Reform Project</strong> <!--| 
		Adapted by: <a href="http://www.silverstriped.com/">SilverStriped</a> |
		Powered by: <a href="http://www.silverstripe.com/">SilverStripe open source CMS</a> |-->
</p>		
		
	</div>	

<!-- footer ends-->
</div>