<?echo $this->slideMenu->render();?>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.selectboxes.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.checkboxes.js"></script>
<style type="text/css">
<!--
// -->
</style>
<script type="text/javascript">
$(document).ready(function() {
	$('ul.sf-menu').superfish();
	
	var currentNode = "<?echo $this->currentNode;?>";
	
	$("#lkEditFolder").click(function(){ 
		var aGuid = getCheckedCheckBox("frmFolders");
		if(aGuid.length!=1)
			alert('You must select ONE Folder to edit')
		else
		{
			if(aGuid[0]=="root")
				alert('Can not edit ROOT folder.')
			else
				window.location = "<?echo KUTU_ROOT_URL;?>/admin/dms_folder/edit/guid/"+aGuid[0]+"/node/"+currentNode;
		}
		
	});
	$("#lkMoveFolder").click(function(){ 
		var aGuid = getCheckedCheckBox("frmFolders");
		for (var i = 0; i < aGuid.length; i++){ 
		         if(aGuid[i]==currentNode && aGuid.length>1)
					{
			 			alert('You can not move current folder with some of its sub folders.');
						return false;
					}
		      }
		var listGuid = '';
		for (var i = 0; i < aGuid.length; i++){ 
		         listGuid += "/guid/" + aGuid[i] ; 
		      }
		if(aGuid.length==0)
			listGuid += "/guid/" + currentNode ;
		window.location = "<?echo KUTU_ROOT_URL;?>/admin/dms_folder/move"+listGuid+"/backToNode/"+currentNode;
		
	});
	$("#lkDeleteFolder").click(function(){ 
		var aGuid = getCheckedCheckBox("frmFolders");
	
		var listGuid = '';
		for (var i = 0; i < aGuid.length; i++){ 
		         listGuid += "/guid/" + aGuid[i] ; 
		      }
		if(aGuid.length==0)
		{
			alert('NO FOLDERS SELECTED');
			return false;
		}
		else
		{
			if(confirm ('Are you sure you want to delete these '+ aGuid.length +' folder(s)?'))
			{
				window.location = "<?echo KUTU_ROOT_URL;?>/admin/dms_folder/delete"+listGuid;
			}
		}
		
		return false;
		
	});
	
	getCheckedCheckBox = function (elementId)
			{
				var content = [];
				var aGuid = new Array();
				var iCount=0;
				$('#' + elementId + ' input').each(function(){
					var el = $(this);
					if ( (el.attr('type').toLowerCase() == 'radio'))
					{
						if ( this.checked )
						{
							content.push([
								'"', el.attr('name'), '": ',
								'value="', ( this.value ), '"',
								( this.disabled ? ', disabled' : '' )
							].join(''));
							aGuid[iCount]=this.value;
							iCount++;
						}
					}
					else
					{
						content.push([
							'"', el.attr('name') + ' '+el.attr('value'), '": ',
							( this.checked ? 'checked' : 'not checked' ), 
							( this.disabled ? ', disabled' : '' )
						].join(''));
						if ( this.checked )
						{
							aGuid[iCount]=el.attr('value');
							iCount++;
						}
					}
					
				});
				return aGuid;
			}
			
	getOnlyOneCheckBox = function (elementId)
			{
				var aGuid = getCheckedCheckBox(elementId);

				if(aGuid.length>1)
				{
					alert('You can select ONLY ONE User to edit');
				}
				else
				{	
					if(aGuid.length==0)
						alert('You must select ONE User to edit')
					else
						return aGuid[0];
				}
				return false;
			}

	
	
});
</script>
<hr class="space">
<h2 class="alt">Document Management</h2>
<ul class="sf-menu">
	<li class="current">
		<a href="#">Select</a>
		<ul>
			<li><a href="#">None</a></li>
			<li><a href="#">All</a></li>
		</ul>
	</li>
	<li>
		<a href="<?echo KUTU_ROOT_URL;?>/admin/dms_folder/new/node/<?echo $this->currentNode;?>">New</a>
	</li>
	<li>
		<a href="#" id="lkEditFolder" name="lkEditFolder">Edit</a>
	</li>
	<li>
		<a href="#" id="lkMoveFolder" name="lkMoveFolder">Move to</a>
	</li>
	<li>
		<a href="<?echo KUTU_ROOT_URL;?>/admin/dms/search-folder" id="lkSearchFolder" name="lkSearchFolder">Search Folder</a>
	</li>
	<li>
		<a href="#">More</a>
		<ul>
			<li>
				<a href="#" id="lkDeleteFolder" name="lkDeleteFolder">Delete</a>
			</li>
		</ul>
	</li>	
</ul>
<div class="span-24 last">
	<hr class="space">
	<?echo $this->widget2->render();?>
	<div style="padding-top:5px;"></div>
	<?echo $this->widget1->render();?>
</div>
<hr class="space">
<script type="text/javascript">
$(document).ready(function() {
	
	
	$("#lkSelectAllCatalogs").click(function(){ 
		
		$("#frmCatalogs").checkCheckboxes();
	});
	$("#lkSelectNoneCatalogs").click(function(){ 
		
		$("#frmCatalogs").unCheckCheckboxes();
	});
		
	
	$("#lkEditCatalog").click(function(){ 
		var aGuid = getCheckedCheckBox("frmCatalogs");
		if(aGuid.length!=1)
			alert('You must select ONE Catalog to edit')
		else
		{
			if(aGuid[0]=="root")
				alert('Can not edit ROOT folder.')
			else
				window.location = "<?echo KUTU_ROOT_URL;?>/admin/dms_catalog/edit/guid/"+aGuid[0]+"/node/<?echo $this->currentNode;?>";
		}
		return false;
		
	});
	$("#lkMoveCatalog").click(function(){ 
		var aGuid = getCheckedCheckBox("frmCatalogs");
	
		var listGuid = '';
		for (var i = 0; i < aGuid.length; i++){ 
		         listGuid += "/guid/" + aGuid[i] ; 
		      }
		if(aGuid.length==0)
		{
			alert('NO CATALOGS SELECTED');
			return false;
		}
		window.location = "<?echo KUTU_ROOT_URL;?>/admin/dms_catalog/movetofolder"+listGuid+"/sourceNode/"+"<?echo $this->currentNode;?>";
		return false;
		
	});
	$("#lkCopyCatalog").click(function(){ 
		var aGuid = getCheckedCheckBox("frmCatalogs");
	
		var listGuid = '';
		for (var i = 0; i < aGuid.length; i++){ 
		         listGuid += "/guid/" + aGuid[i] ; 
		      }
		if(aGuid.length==0)
		{
			alert('NO CATALOGS SELECTED');
			return false;
		}
		window.location = "<?echo KUTU_ROOT_URL;?>/admin/dms_catalog/copytofolder"+listGuid+"/sourceNode/"+"<?echo $this->currentNode;?>";
		return false;
		
	});
	$("#lkDeleteCatalog").click(function(){ 
		var aGuid = getCheckedCheckBox("frmCatalogs");
	
		var listGuid = '';
		for (var i = 0; i < aGuid.length; i++){ 
		         listGuid += "/guid/" + aGuid[i] ; 
		      }
		if(aGuid.length==0)
		{
			alert('NO CATALOGS SELECTED');
			return false;
		}
		else
		{
			if(confirm ('Are you sure you want to delete these '+ aGuid.length +' catalog(s)?'))
			{
				window.location = "<?echo KUTU_ROOT_URL;?>/admin/dms_catalog/delete"+listGuid;
			}
		}
		
		return false;
		
	});
	$("#lkAlterCreatedModDateCatalog").click(function(){ 
		var aGuid = getCheckedCheckBox("frmCatalogs");
		if(aGuid.length!=1)
			alert('You must select ONE Catalog to edit')
		else
		{
			if(aGuid[0]=="root")
				alert('Can not edit ROOT folder.')
			else
				window.location = "<?echo KUTU_ROOT_URL;?>/admin/dms_catalog/alterdate/guid/"+aGuid[0];
		}
		return false;
		
	});
	
});
</script>
<ul class="sf-menu">
	<li class="current">
		<a href="#">Select</a>
		<ul>
			<li><a href="#" id="lkSelectNoneCatalogs" name="lkSelectNoneCatalogs">None</a></li>
			<li><a href="#" id="lkSelectAllCatalogs" name="lkSelectAllCatalogs">All</a></li>
		</ul>
	</li>
	<li>
		<a href="#">New</a>
		<ul>
			<li><a href="<?echo KUTU_ROOT_URL;?>/admin/dms_catalog/new/node/<?echo $this->currentNode;?>/profile/article">Article</a></li>
			<li><a href="<?echo KUTU_ROOT_URL;?>/admin/dms_catalog/new/node/<?echo $this->currentNode;?>/profile/kutu_peraturan">Law and Regulation</a></li>
			<li><a href="#">Judgement</a></li>
			<li><a href="<?echo KUTU_ROOT_URL;?>/admin/dms_catalog/new/node/<?echo $this->currentNode;?>/profile/legal_memoranda">Legal Memoranda</a></li>
		</ul>
	</li>
	<li>
		<a href="#" id="lkEditCatalog" name="lkEditCatalog">Edit</a>
	</li>
	<li>
		<a href="#" id="lkMoveCatalog" name="lkMoveCatalog">Move to</a>
	</li>
	<li>
		<a href="<?echo KUTU_ROOT_URL;?>/admin/dms/search" id="lkSearchCatalog" name="lkSearchCatalog">Search Catalog</a>
	</li>
	<li>
		<a href="#">More</a>
		<ul>
			<li>
				<a href="#" id="lkDeleteCatalog" name="lkDeleteCatalog">Delete</a>
				<!--<ul>
					<li><a href="#">short</a></li>
					<li><a href="#">short</a></li>
					<li><a href="#">short</a></li>
					<li><a href="#">short</a></li>
					<li><a href="#">short</a></li>
				</ul>-->
			</li>
			<li>
				<a href="#" id="lkCopyCatalog" name="lkCopyCatalog">Copy to</a>
			</li>
			<li>
				<a href="#" id="lkAlterCreatedModDateCatalog" name="lkAlterCreatedModDateCatalog">Alter Creation/<br>Modification Date</a>
			</li>
		</ul>
	</li>	
</ul>

<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/lib/jquery/pagination.css" />
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.pagination.js"></script>
<script>

$(document).ready(function(){
	
	var isFirstTime = 1;
	
	// First Parameter: number of items
	// Second Parameter: options object
	var myPageIndex = 0;
	var itemsPerPage = <?echo $this->itemsPerPage;?>;
	var currentOffset = <?echo $this->offset;?>;
	var limit = <?echo $this->limit;?>;
	var currentNode = "<?echo $this->currentNode;?>";
	var totalItems = <?echo $this->totalItems;?>;
	var sort = "<?echo $this->sort;?>";
	
	
	var tmpCurrentPageIndex = currentOffset/itemsPerPage;
	
	$("#catalogPagination").pagination(totalItems, 
	{items_per_page:itemsPerPage, callback:handlePaginationClick, current_page:tmpCurrentPageIndex}
	);
	
	function handlePaginationClick(new_page_index, pagination_container) 
	{
		if(!isFirstTime)
		{
			myPageIndex = new_page_index;
			var nextOffset = (itemsPerPage * myPageIndex);
		
			$("#sOffset").val(nextOffset);
			$("#frmSearch").submit();
			
			var url = "<?echo KUTU_ROOT_URL;?>/admin/dms/explore/node/"+currentNode+"/offset/"+nextOffset+"/limit/"+limit+"/sort/"+sort+"/";
			window.location = url;
		}
		isFirstTime = 0;
		return false;
	}
	
	
});

</script>
<h3 class="alt">Number of Catalogs: <?php echo $this->hits->response->numFound;?> Record(s)</h3>
<hr class="space">
<form id="frmCatalogs" name="frmCatalogs">
<?php foreach ($this->hits->response->docs as $hit) { ?>
	<div class='span-2'><input type='checkbox' name='catalogGuid' id='catalogGuid' value='<?php echo $hit->id;?>'>&nbsp;<IMG src='<?php echo KUTU_ROOT_URL.'/common/images/fb/note.png' ?>' width=24 height=24 border=0 align=absmiddle /></div>
	<div class='span-22 last'>
		<p>
			<?php if($hit->profile == 'kutu_doc'){?>
				<a href="<?php echo KUTU_ROOT_URL;?>/browser/downloadfile/guid/<?php echo $hit->id;?>"><div class="searchResultTitle">File: <?php try {echo $hit->title;} catch (Exception $e) {echo '';}?></div></a>
			<?php } else { ?>
					<a href="<? echo KUTU_ROOT_URL;?>/admin/dms_catalog/details/guid/<?php echo $hit->id;?>/node/<?echo $this->currentNode;?>"><?php try {echo $hit->title;} catch (Exception $e) {echo 'No-Title';}?></a>
			<?php }?>
			<br>
			<?php try {echo @$hit->subTitle;} catch (Exception $e) {echo '';}?>
			<br>
			<strong>PRICE:</strong> USD <?php echo $this->bpm->getPrice($hit->id);?>
			<br>
			Last modified on: <?php try {echo @$hit->modifiedDate;} catch (Exception $e) {echo '';}?>
		</p>
	</div>
	<hr>
<?php }; ?>
</form>
<div class="span-24 last">
	<table width='100%'>
		<tr>
			<td width=35%>&nbsp;</td>
			<td align=right><div id='catalogPagination' class="pagination"></div></td>
		</tr>
	</table>
</div>






