<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/lib/jquery/pagination.css" />
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.pagination.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/js/smooth.scroller.js"></script>
<div id='aku'></div>
<a name='a' id='a'></a>
<?echo 'Number of record(s): '.$this->aData['totalCount'];?>
<br>&nbsp;
<div class="container">
	<div class="span-15">
		<div id='catalogContent'>

		</div>
	</div>
</div>

<table width='100%'>
	<tr>
		<td width=35%>&nbsp;</td>
		<td align=right><div id='catalogPagination' class="pagination"></div></td>
	</tr>
</table>
<script>

$(document).ready(function(){
	
	var isFirstTime = 1;
	
	
	// First Parameter: number of items
	// Second Parameter: options object
	var myPageIndex = 0;
	
	$("#catalogPagination").pagination(<?php echo $this->aData['totalCount'];?>, 
	{items_per_page:<?php echo $this->aData['limit'];?>, callback:handlePaginationClick}
	);
	
	function handlePaginationClick(new_page_index, pagination_container) 
	{
		myPageIndex = new_page_index;
		myStart = (<?php echo $this->aData['limit'];?> * myPageIndex);
		
		if(true)
		{
			//$.get('<?echo KUTU_ROOT_URL;?>/api/catalog/getcatalogsinfolder/folderGuid/2/start/0/limit/20', '', showResult, "text");
			if($('#tblCatalogPager-'+myPageIndex).length==0)
			{
				$('#message_box').show();
				$.getJSON('<?echo KUTU_ROOT_URL;?>/api/catalog/getcatalogsinfolder/folderGuid/<?php echo $this->aData['folderGuid'];?>/start/'+myStart+'/limit/<?php echo $this->aData['limit'];?>', '', testJson);
			}
			else
				showCatalogContent();
		}
		return false;
	}
	function testJson(res)
	{
		size = res.catalogs.length;
		var tblRow = "<a name='a-"+myPageIndex+"' ></a>"+'<div class="tblCatalogPager" id="tblCatalogPager-'+myPageIndex+'">';
		for(i=0;i<size;i++)
		{
			tblRow += 
				"<div class='span-1'>" + "<input type='checkbox' name='guid' id='guid' value='"+res.catalogs[i].guid+"'>" + "</div>"
				+"<div class='span-2'><a href='<? echo KUTU_ROOT_URL;?>/dms/catalog/"+res.catalogs[i].guid+"/node/"+res.folderGuid+"'><IMG src='<?php echo KUTU_ROOT_URL.'/common/images/fb/note.png' ?>' width=24 height=24 border=0 align=absmiddle /></a></div>"
				+"<div class='span-12 last'><a href='<? echo KUTU_ROOT_URL;?>/dms/catalog/"+res.catalogs[i].guid+"/node/"+res.folderGuid+"'>"+res.catalogs[i].title+"</a>"
				+"<div>"+res.catalogs[i].subTitle+"</div>"
				+"<div class='' style='padding-top:10px'></div>"
				+"</div><hr>";
				
		}
		tblRow += "</div>";
		$(tblRow).appendTo("#catalogContent");
		showCatalogContent();
		$('#message_box').fadeOut();
		
		
	}
	function testJsonORI(res)
	{
		size = res.catalogs.length;
		var tblRow = "<a name='a-"+myPageIndex+"' ></a>"+'<table cellpadding="0" cellspacing="0" width="100%" class="tblCatalogPager" id="tblCatalogPager-'+myPageIndex+'">';
		for(i=0;i<size;i++)
		{
			tblRow += 
				"<tr><td colspan='2'><IMG src='<?php echo KUTU_ROOT_URL.'/spacer.gif' ?>' border=0 height='10px' align=absmiddle /></td></tr>"
				+"<tr valign=top>"
				+"<td width=50 class='row_list'><input type='checkbox' name='listProductID' value='2'> <a href='<? echo KUTU_ROOT_URL;?>/dms/catalog/"+res.catalogs[i].guid+"/node/"+res.folderGuid+"'><IMG src='<?php echo KUTU_ROOT_URL.'/common/images/doc-s.png' ?>' border=0 align=absmiddle /></a></td>"
				+"<td class='row_list'><a href='<? echo KUTU_ROOT_URL;?>/dms/catalog/"+res.catalogs[i].guid+"/node/"+res.folderGuid+"'>"+res.catalogs[i].title+"</a>"
				+"<div>"+res.catalogs[i].subTitle+"</div>"
				+"<div class='' style='padding-top:10px'></div>"
				+"</td>"
				+"</tr>";
				
		}
		tblRow += "</table>";
		$(tblRow).appendTo("#catalogContent");
		showCatalogContent();
		$('#message_box').fadeOut();
		
		
	}
	function showCatalogContent()
	{
		$('.tblCatalogPager').hide();
		$('#tblCatalogPager-'+myPageIndex).show();
		if(!isFirstTime)
			//window.location.hash = '#a-'+myPageIndex;
			Scroller.scroll();
		isFirstTime = 0;
	}
	
	
});



</script>