<script type="text/javascript">
	$(document).ready(function(){
		$('#menu').flickrmenu();
	});
</script>
<table width='100%' cellpadding="0" cellspacing="0">
	<tr valign="top">
		<td width="100%" class="" style="padding-left:0px;border-bottom:1px solid #E5E5E5;">
			<div id="menu" >
				  <ul>
					<li>
				      <span class="head_menu">
				        <a href="#">Select</a>
				        <img src="<?echo KUTU_ROOT_URL;?>/common/images/arrow.png" width="18" height="15" align="top" class="arrow" />
				      </span>
				      <div class="sub_menu">
				        <a href="#">None</a>
				        <a href="#">All</a>
				      </div>
				    </li>
				    <li>
				      <span class="head_menu">
				        <a href="<?echo KUTU_ROOT_URL;?>/admin/user/add">New</a>
				      </span>
				    </li>
					<li>
				      <span class="head_menu">
				        <a href="#">Edit</a>
				      </span>
				    </li>
				    <li>
				      <span class="head_menu">
				        <a href="#">View</a>
				        <img src="<?echo KUTU_ROOT_URL;?>/common/images/arrow.png" width="18" height="15" align="top" class="arrow" />
				      </span>
				      <div class="sub_menu">
				        <a href="#">All</a>
				        <a href="#">Active</a>
				        <a href="#">Inactive</a>
						<a href="#">Banned</a>
				      </div>
				    </li>
					<li>
				      <span class="head_menu">
				        <a href="#">More</a>
				        <img src="<?echo KUTU_ROOT_URL;?>/common/images/arrow.png" width="18" height="15" align="top" class="arrow" />
				      </span>
				      <div class="sub_menu">
				        <a href="#">Manage Group</a>
				        <a href="#">Show Orders</a>
				      </div>
				    </li>
					<li>
				      <span class="head_menu">
				        <a href="<?echo KUTU_ROOT_URL;?>/admin/user/browse">Show All</a>
				      </span>
				    </li>
				  </ul>
				</div>
			
		</td>
	</tr>
</table>