<script type="text/javascript">
$(document).ready(function() {
	$("#frmChangePwd").validate({
		rules: {
			password: {
				required: true,
				minlength: 5
			},
			passwordConfirm: {
				required: true,
				minlength: 5,
				equalTo: "#password"
			},
			oldPassword: {
				required: true,
				remote: "<? echo KUTU_ROOT_URL;?>/site/myaccount_api/verifyoldpassword/"
			},
			dateformat: "required",
			terms: "required"
		},
		messages: {
			password: {
				required: "Provide a password",
				rangelength: jQuery.format("Enter at least {0} characters")
			},
			passwordConfirm: {
				required: "Repeat your password",
				minlength: jQuery.format("Enter at least {0} characters"),
				equalTo: "Enter the same password as above"
			},
			oldPassword	: {
				required: "Please enter your old password",
				remote: jQuery.format("Your old password does not match")
			},
			dateformat: "Choose your preferred dateformat",
			terms: " "
		}
		
		
	});
	
	var message = "<?echo $this->message;?>";
	if(message!="")
	{
		alert (message);
	}
});
</script>
<h2 class="alt">My Account: Edit Profile</h2>
<hr>
<div class="span-15 prepend-1 colborder">
	<form class="" id="frmChangePwd" name="frmChangePwd" method="post" action="">
		<fieldset>
			<legend>Login Info</legend>
			<p>
				<label for="username">Username</label>
				<?echo $this->username;?>
			</p>
			<p>
				<label for="oldPassword">Old Password</label>
				<input id="oldPassword" name="oldPassword" type="password" class="required" maxlength="50" value="" />
			</p>
			<p>
				<label for="password">New Password</label>
				<input id="password" name="password" type="password" class="required" maxlength="50" value="" />
			</p>
			<p>
				<label for="passwordConfirm">Confirm Password</label>
				<input id="passwordConfirm" name="passwordConfirm" type="password" class="required" maxlength="50" value="" />
			</p>
			<p>
				<input class="submit" type="submit" value="Submit"/>
			</p>
		</fieldset>
	</form>

</div>
<div class="span-7 last">
	<?echo $this->widget1->render();?>
</div>