<?php
/**
 * @package kutump
 * @copyright 2008-2009 hukumonline.com
 * @author Nihki Prihadi <nihki@hukumonline.com>
 *
 * $Id: footer.phtml 2009-02-05 00:31: $
 */
?>

<html>
<body>
<table width="982" border="0" cellpadding="0" cellspacing="0" background="<?php echo KUTU_ROOT_URL; ?>/view-resources/img/tile_bawah.jpg">
<tr>
	<td>
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
    	<td width="984">&nbsp;</td>
    	<td width="984" align="left" valign="top">
    	<table width="940" border="0" cellspacing="0" cellpadding="0">
      	<tr>
        	<td width="244" height="80" align="left" valign="top" class="td_footer">
        	<div id="footer">
          	<table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
            	<td><img src="<?php echo KUTU_ROOT_URL; ?>/view-resources/img/tfooter_talks.jpg" vspace="0" width="104" border="0" height="46" hspace="0"  align="left"/></td>
            </tr>
            <tr>
              	<td>
              	<img src="<?php echo KUTU_ROOT_URL; ?>/view-resources/img/member/foto40x40.jpg" vspace="0" width="40" border="0" height="40" hspace="0"  align="left" class="image"/>
                <a href="#" class="linkbawah">Hukumonline Legal Directory (HOLD) Online memuat koleksi data hukum elektronik terlengkap di Indonesia.</a><<br /><hr />
                <img src="<?php echo KUTU_ROOT_URL; ?>/view-resources/img/member/foto40x40.jpg" vspace="0" width="40" border="0" height="40" hspace="0"  align="left" class="image"/>
                <a href="#" class="linkbawah">Hukumonline Legal Directory (HOLD) Online memuat koleksi data hukum elektronik terlengkap di Indonesia.</a><br /><hr />
                <img src="<?php echo KUTU_ROOT_URL; ?>/view-resources/img/member/foto40x40.jpg" vspace="0" width="40" border="0" height="40" hspace="0"  align="left" class="image"/>
                <a href="#" class="linkbawah">Hukumonline Legal Directory (HOLD) Online memuat koleksi data hukum elektronik terlengkap di Indonesia.</a><br /><hr />
          		</td>
            </tr>
          	</table>
        	</div>
        	</td>
        	<td width="3" height="80" align="left" valign="top">&nbsp;</td>
        	<td width="244" height="80" align="left" valign="top" class="td_footer">
        	<div id="footer">
        	<table width="100%" border="0" cellspacing="0" cellpadding="0">
  			<tr>
    			<td><img src="<?php echo KUTU_ROOT_URL; ?>/view-resources/img/tfooter_agenda.jpg" vspace="0" width="117" border="0" height="46" hspace="0"  align="left"/></td>
 	 		</tr>
  			<tr>
    			<td><?php //echo $this->action('agenda','widgets_polling'); ?></td>
			</tr>
			</table>
            </div>
            </td>
        	<td width="2" height="80"  valign="top">&nbsp;</td>
        	<td width="244" height="80" align="left" valign="top" class="td_footer">
        	<div id="footer">
        	<table width="100%" border="0" cellspacing="0" cellpadding="0">
  			<tr>
    			<td><img src="<?php echo KUTU_ROOT_URL; ?>/view-resources/img/tfooter_komunitas.jpg" vspace="0" width="148" border="0" height="46" hspace="0"  align="left"/></td>
  			</tr>
  			<tr>
	    		<td>
	    		<img src="<?php echo KUTU_ROOT_URL; ?>/view-resources/img/member/foto40x40.jpg" vspace="0" width="40" border="0" height="40" hspace="0"  align="left" class="image"/>
	        	<a href="#" class="linkbawah">Hukumonline Legal Directory (HOLD) Online memuat koleksi data hukum elektronik terlengkap di Indonesia.</a><br /><hr>
	        	<img src="<?php echo KUTU_ROOT_URL; ?>/view-resources/img/member/foto40x40.jpg" vspace="0" width="40" border="0" height="40" hspace="0"  align="left" class="image"/>
	        	<a href="#" class="linkbawah">Hukumonline Legal Directory (HOLD) Online memuat koleksi data hukum elektronik terlengkap di Indonesia.</a><br /><hr>
	        	<img src="<?php echo KUTU_ROOT_URL; ?>/view-resources/img/member/foto40x40.jpg" vspace="0" width="40" border="0" height="40" hspace="0"  align="left" class="image"/>
	        	<a href="#" class="linkbawah">Hukumonline Legal Directory (HOLD) Online memuat koleksi data hukum elektronik terlengkap di Indonesia.</a><hr><br />
	        	</td>
  			</tr>
			</table>
            </div>
            </td>
        	<td width="3" height="80"  valign="top">&nbsp;</td>
        	<td width="244" height="80" align="left" valign="top" class="td_footer">
        	<div id="footer">
        	<table width="100%" border="0" cellspacing="0" cellpadding="0">
  			<tr>
    			<td><img src="<?php echo KUTU_ROOT_URL; ?>/view-resources/img/tfooter_suarapembaca.jpg" vspace="0" width="177" border="0" height="46" hspace="0"  align="left"/></td>
  			</tr>
  			<tr>
	    		<td>
	    		<img src="<?php echo KUTU_ROOT_URL; ?>/view-resources/img/foto.jpg" vspace="0" width="70" border="0" height="70" hspace="0"  align="left" class="image"/>
	        	<a href="#" class="linkbawah">Duis dictum elementum turpis. Etiam quis lectus sed magna hendrerit pharetra. Nunc pharetra elementum ante. Nam ut lacus id ante egestas dignissim. Nam ut lacus id ante egestas dignissim. <br /> Duis dictum elementum turpis. Etiam quis lectus sed magna hendrerit pharetra. Nunc pharetra elementum ante. Nam ut lacus id ante egestas dignissim. Nam ut lacus id ante egestas dignissim.</a><br />
	        	</td>
  			</tr>
			</table>
            </div>
            </td>
      	</tr>
    	</table>
    	</td>
    	<td width="984">&nbsp;</td>
  	</tr>
  	<tr>
    	<td width="984"></td>
    	<td width="984" align="left" valign="top"></td>
    	<td width="984"></td>
  	</tr>
   	<tr>
    	<td width="984" height="14">&nbsp;</td>
    	<td width="984" align="left" valign="top"></td>
    	<td width="984">&nbsp;</td>
  	</tr>
	</table>
	</td>
</tr>
</table>
<table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#333333">
<tr>
	<td>
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
  	<tr>
    	<td>&nbsp;</td>
    	<td width="984" align="left" valign="top">
    	<div align="center" class="footnote"><br />I  <a href="#" class="footnote">Home</a> I  <a href="#" class="footnote">Tentang Kami</a>  I   <a href="#" class="footnote">Kode Etik</a>  I   <a href="#" class="footnote">Mitra Kami</a> I <br />
      	Informasi yang tersedia di<a href="#" class="footnote"> www.hukumonline.com</a> tidak ditujukan sebagai suatu nasehat hukum,<br />
      	namun hanya memberikan gambaran umum terhadap suatu informasi atau permasalahan hukum yang sedang dihadapi.<br />
      	Akses dan penggunaan situs ini tunduk pada Syarat dan Ketentuan © 2009</div></td>
    	<td>&nbsp;</td>
  	</tr>
	</table>
	</td>
</tr>
</table>
</body>
</html>

