<? 
	// INITIALIZE JCART AFTER SESSION START
	$cart =& $_SESSION['jCart']; if(!is_object($cart)) $cart = new jCart();
	// INCLUDE CONFIG SO THIS SCRIPT HAS ACCESS USER FIELD NAMES
	include(KUTU_ROOT_DIR.'/lib/jcart/jcart-config.php');
	// INCLUDE DEFAULT VALUES SINCE WE NEED TO PASS THE VALUE OF THE UPDATE BUTTON BACK TO jcart.php IF UPDATING AN ITEM QTY
	// IF NO VALUE IS SET IN CONFIG, THERE HAS TO BE A DEFAULT VALUE SINCE SIMPLY CHECKING FOR THE VAR ITSELF FAILS
	include(KUTU_ROOT_DIR.'/lib/jcart/jcart-defaults.php');
?>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jcart/jcart-javascript.php"></script>
<script>
/*
*****************************************
Author: Vivekanand
Website: http://www.developersnippets.com
*****************************************
*/
$(document).ready(function(){
	$(".toggleBtn").click(function(){
			if($("#slideMenu").hasClass('closed')){
				$("#slideMenu").animate({left:0}, 500, function(){
					$(this).removeClass('closed').addClass('opened');
					$("a#toggleLink").removeClass('toggleBtn').addClass('toggleBtnHighlight');
				});
			}//if close
 
			$('#slideMenu').bind("mouseleave",function(){
				$("#slideMenu").animate({left:-300}, 500, function(){
					$(this).removeClass('opened').addClass('closed');
					$("a#toggleLink").removeClass('toggleBtnHighlight').addClass('toggleBtn');
				});
			});//bind close
	});//toggleBtn click close
 
	$("a.anchorLink").click(function () {	
		elementClick = $(this).attr("href");
		destination = $(elementClick).offset().top;
		$("html:not(:animated),body:not(:animated)").animate({ scrollTop: destination}, 1000 );
		return false;
	})
 
	//Mouse Enter Event (that is mouseover event)
	$(".toggleBtn").bind("mouseenter",function(){
			if($("#slideMenu").hasClass('closed')){
				$("#slideMenu").animate({left:0}, 500, function(){
					$(this).removeClass('closed').addClass('opened');
					$("a#toggleLink").removeClass('toggleBtn').addClass('toggleBtnHighlight');
				});
			}//if close
 
			$('#slideMenu').bind("mouseleave",function(){
				$("#slideMenu").animate({left:-300}, 500, function(){
					$(this).removeClass('opened').addClass('closed');
					$("a#toggleLink").removeClass('toggleBtnHighlight').addClass('toggleBtn');
				});
			});//bind close
	});//toggleBtn click close
 
});//ready close
</script>

<div id="slideMenu" class="closed">
	<div class="slideMenuContent">
	<strong>Quick Links</strong>
		<ul>
			<li><a href="#myAnchor" class="anchorLink" title="Anchor Link">Anchor Link</a></li>
			<li><a href="http://www.developersnippets.com/about/" title="About Me">About Me</a> </li>
			<li>Back to Article</li>
		</ul>
		<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. <a href="#">Morbi et risus</a>. Aliquam nisl. Nulla facilisi. Cras accumsan vestibulum ante. Vestibulum sed tortor. Praesent <span class="caps">SMALL CAPS</span> tempus fringilla elit. Ut elit diam, sagittis in, nonummy in, gravida non, nunc. Ut orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam egestas, orci eu imperdiet malesuada, nisl purus fringilla odio, quis commodo est orci vitae justo. Aliquam placerat odio tincidunt nulla. Cras in libero. Aenean rutrum, magna non tristique posuere, erat odio eleifend nisl, non convallis est tortor blandit ligula. Nulla id augue.</p>

		<p>Nullam mattis, odio ut tempus facilisis, metus nisl facilisis metus, auctor consectetuer felis ligula nec mauris. Vestibulum odio erat, fermentum at, commodo vitae, ultrices et, urna. Mauris vulputate, mi pulvinar sagittis condimentum, sem nulla aliquam velit, sed imperdiet mi purus eu magna. Nulla varius metus ut eros. Aenean aliquet magna eget orci. Class aptent taciti sociosqu ad litora.</p>
		<p>Vivamus euismod. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse vel nibh ut turpis dictum sagittis. Aliquam vel velit a elit auctor sollicitudin. Nam vel dui vel neque lacinia pretium. Quisque nunc erat, venenatis id, volutpat ut, scelerisque sed, diam. Mauris ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec mattis. Morbi dignissim sollicitudin libero. Nulla lorem.</p>
		<blockquote>
			<p>Integer cursus ornare mauris. Praesent nisl arcu, imperdiet eu, ornare id, scelerisque ut, nunc. Praesent sagittis erat sed velit tempus imperdiet. Ut tristique, ante in interdum hendrerit, erat enim faucibus felis, quis rutrum mauris lorem quis sem. Vestibulum ligula nisi, mattis nec, posuere et, blandit eu, ligula. Nam suscipit placerat odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Pellentesque tortor libero, venenatis vitae, rhoncus eu, placerat ut, mi. Nulla nulla.</p>
		</blockquote>
		<p>Maecenas vel metus quis magna pharetra fermentum. <em>Integer sit amet tortor</em>. Maecenas porttitor, pede sed gravida auctor, nulla augue aliquet elit, at pretium urna orci ut metus. Aliquam in dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, tellus id ornare posuere, quam nunc accumsan turpis, at convallis tellus orci et nisl. Phasellus congue neque a lorem.</p>
		
	</div>
	<a style="top:100px; right: -42px;" href="#" class="toggleBtn" id="toggleLink"></a>
</div>
<br>
<?echo $this->widget3->render();?>
<h2 class="alt">LGS Legal Database</h2>
<hr>
<div class="span-15 prepend-1 colborder">
	<?echo $this->widget1->render();?>
	<?echo $this->widget2->render();?>
	<!--<div class="span-1"><IMG src='<?php echo KUTU_ROOT_URL.'/common/images/fb/note.png' ?>' width=24 height=24 border=0 align=absmiddle /></div>
	<div class="span-10">
		<p>Peraturan Pemerintah Nomor 2 Tahun 2009<br>Perlindungan Anak<br><strong>Price: USD 20.0</strong></p>		
	</div>
	<div class="span-4 last">
		<form method="post" action="" class="jcart">
			<fieldset style="border:0;">
				<div style="display:none">
				<input type="hidden" name="my_item_id" value="1" />
				<input type="hidden" name="my_item_name" value="Soccer Ball" />
				<input type="hidden" name="my_item_price" value="25.00" />
				<input type="text" name="my_item_qty" value="1" size="3" />
				</div>
				<input type="submit" name="my_add_button" value="add to cart" class="button" />
			</fieldset>
		</form>	
	</div>
	<hr>
	<div class="span-1"><IMG src='<?php echo KUTU_ROOT_URL.'/common/images/fb/note.png' ?>' width=24 height=24 border=0 align=absmiddle /></div>
	<div class="span-10">
		<p>Peraturan Pemerintah Nomor 2 Tahun 2009<br>Perlindungan Anak<br><strong>Price: USD 20.0</strong></p>
		
	</div>
	<div class="span-4 last">
		<form method="post" action="" class="jcart">
			<fieldset style="border:0;">
				<div style="display:none">
				<input type="hidden" name="my_item_id" value="lt232aanfsgg" />
				<input type="hidden" name="my_item_name" value="Peraturan Pemerintah Nomor 2 Tahun 2009" />
				<input type="hidden" name="my_item_price" value="25.00" />
				<input type="text" name="my_item_qty" value="1" size="3" />
				</div>
				<input type="submit" name="my_add_button" value="add to cart" class="button" />
			</fieldset>
		</form>
	</div>
	<hr>-->
	
</div>
<div class="span-7 last">
	
	<h3>My <span class="alt">Cart</span> </h3>
	<div id="sidebar">
		<?php $cart->display_cart($jcart);?>
	</div>
	<hr class="space">
	<h3>About<span class="alt"> Legal Database</span> </h3>
	<p>Click <a href="<?echo KUTU_ROOT_URL;?>/site/index/about">here</a> to get more information about LGS Legal Database</p>
	<hr class="space">
	<h3>Most <span class="alt">Downloaded</span> </h3>
	<p>Here is the list of the most downloaded documents</p>
	<hr class="space">
	<h3>Did <span class="alt">You know?</span> </h3>
	<p>Facts just about anything...</p>
	<hr class="space">
	<h3>Your <span class="alt">Documents</span> </h3>
	<p>Here is the list of the documents you have bought before.</p>
</div>