<script type="text/javascript">
$(document).ready(function() {
	$("#username").ajaxSend(function(evt, request, settings){
	   //$(this).append("<li>Starting request at " + settings.url + "</li>");
		//alert("sending data..");
	 });
	
	$("#frmSignup").validate({
		rules: {
			firstname: "required",
			username: {
				required: true,
				minlength: 2
				//remote: "<?php echo KUTU_ROOT_URL;?>/api/user/isusernameavailable/"
			},
			password: {
				required: true,
				minlength: 5
			},
			passwordConfirm: {
				required: true,
				minlength: 5,
				equalTo: "#password"
			},
			email: {
				required: true,
				email: true
				//remote: "emails.php"
			},
			dateformat: "required",
			terms: "required"
		},
		messages: {
			firstname: "Enter your Firstname",
			username: {
				required: "Enter a username",
				minlength: jQuery.format("Enter at least {0} characters")
				//remote: jQuery.format("{0} is already in use")
			},
			password: {
				required: "Provide a password",
				rangelength: jQuery.format("Enter at least {0} characters")
			},
			passwordConfirm: {
				required: "Repeat your password",
				minlength: jQuery.format("Enter at least {0} characters"),
				equalTo: "Enter the same password as above"
			},
			email: {
				required: "Please enter a valid email address",
				minlength: "Please enter a valid email address",
				remote: jQuery.format("{0} is already in use")
			},
			dateformat: "Choose your preferred dateformat",
			terms: " "
		}
		
		
	});
	
	var message = "<?echo $this->message;?>";
	if(message!="")
	{
		alert (message);
	}
});
</script>
<hr>
<div container>
	<div class="span-33 append-2 prepend-2 last">
		<h2 class="alt">Forget Password</h2>
	</div>
</div>
<hr>
<div class="span-33 append-2 prepend-2">
	<form id="frmSignup" action="" method="post">

	      	<fieldset>

	      		<legend>Member Info | * denotes required fields</legend>
				<p>
					<label for="username">* Username</label><br>
					<input type='text' id="username" name="username" class="text required" minlength="2" />
				</p>
	      		<p><label for="email">* Your Registered Email</label> (The one that you are using for your LGS Online account)<br>
	      		  <input type="text" class="text required email" name="email" id="email" value=""></p>
				
	      		<p><input type="submit" value="Submit"></p>

	      	</fieldset>
	      </form>
</div>
<br>&nbsp;