<div class="container">
	<div class="span-18" style="margin:0.8em 0 0.5em 0;">
		<IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/logo-lgs-top.png" />
	</div>
	<div class="span 19 last" style="text-align:right;margin:0.8em 0 0.8em 0;">
		<div class=""><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/logo-lgsol-top.png" /></div>
	</div>
</div>

<div class="darker"></div>
<div style="background:#fd9a01">
	<div class="container">
		<!--<div class="darker"></div>-->
	
			<div class="span-37 last" style="background: ;">
					<?echo $this->action('mainmenu','component','site')?>
			</div>
		</div>
	</div>
</div>
<div class="darker">
	
</div>
<div class="container">
	<div class="span-37 last" style="background: #000">
		<IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/header.png" />
	</div>
</div>