<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php $this->headLink()->appendStylesheet(KUTU_ROOT_URL.'/common/modules/identity/styles/identity.css'); ?>
<?= $this->headLink() ?>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="description" content="Identity Page" />
<meta http-equiv="Copyright" content="langIT" />
<meta name="author" content="langIT" />
<meta name="language" content="English" />
<meta name="webcrawlers" content="all" />
<meta name="rating" content="general" />
<meta name="spiders" content="all" />
<meta name="robots" content="all" />
<LINK href="<?php echo KUTU_ROOT_URL; ?>/common/images/hole_small.ico" rel="shortcut icon">
<title>Hukumonline-ID</title>
</head>
<body>
<div id="header">
<img src="<?php echo KUTU_ROOT_URL; ?>/common/modules/identity/images/holid.jpg" alt="mnutopshadow" />
<div id="slogan">Welcome to HukumonlineID</div>
</div>
<div id="path">
<a href="<?php //echo $this->getKutuRootUrl(); ?>">Home</a>
&nbsp;&nbsp;
<a href="http://www.hukumonline.com">Indonesia version</a>
</div>

<?php echo $this->layout()->content; ?>

<div id="footer">

<div id="copyrightdesign">
<a href="<?php //echo $this->getKutuRootUrl();?>/app/servers/identity/account/feedback">Feedback</a> | <a href="http://hukumonline.blogspot.com/">Blog</a> | Copyright &copy; 2008 Hukumonline 
</div>

<div id="footercontact">
<a href="<?php //echo $this->getKutuRootUrl(); ?>/app/dms/browser/detail/guid/lt48475fee7b676">Contact</a>
</div>

</div>

</body>
</html>
