<html dir="ltr" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- Framework CSS -->
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/modules/dms/styles/screen.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/modules/dms/styles/print.css" type="text/css" media="print">
  <!--[if IE]><link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/modules/dms/styles/ie.css" type="text/css" media="screen, projection"><![endif]-->

<!--[if IE]><script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/js/excanvas.js"></script><![endif]-->
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.roundcorners.js"></script>
<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.jgrowl.css" />
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.jgrowl.js"></script>

<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.idtabs.js"></script>
<style type="text/css">

/*Credits: Dynamic Drive CSS Library */
/*URL: http://www.dynamicdrive.com/style/ */

.invertedshiftdown3{
padding: 0;
width: 100%;
border-bottom: 1px solid #bcbcbb; /*Highlight red color theme*/
background: transparent;
voice-family: "\"}\"";
voice-family: inherit;
}

.invertedshiftdown2{
padding: 0;
width: 100%;
border-top: 2px solid black; /*Highlight red color theme*/
background: transparent;
voice-family: "\"}\"";
voice-family: inherit;
}

.invertedshiftdown2 ul{
margin:0;
margin-left: 270px; /*margin between first menu item and left browser edge*/
padding: 0;
list-style: none;
}

.invertedshiftdown2 li{
display: inline;
margin: 0 2px 0 0;
padding: 0;
text-transform:uppercase;
}

.invertedshiftdown2 a{
float: left;
display: block;
font: 11px Arial;
color: black;
text-decoration: none;
margin: 0 1px 0 0; /*Margin between each menu item*/
padding: 5px 10px 5px 10px; /*Padding within each menu item*/
background-color: white; /*Default menu color*/
border-bottom: 1px solid white;
border-right: 1px solid #bcbcbb;
}

.invertedshiftdown2 a:hover{
/*background-color: #D10000; /*Highlight red color theme*/
padding-top: 10px; /*Set padding-top value to default's padding-top + padding-bottom */
padding-bottom: 0; /*Set padding-bottom value to 0 */
border-bottom-color: #D10000; /*Highlight red color theme*/
color: white;*/
text-decoration: none;
margin: 0 1px 0 0; /*Margin between each menu item*/
padding: 5px 10px 5px 10px; /*Padding within each menu item*/
background-color: lightblue; /*Default menu color*/
border-bottom: 1px solid white;
}

.invertedshiftdown2 .current a{ /** currently selected menu item **/
/*background-color: #D10000; /*Highlight red color theme*/
padding-top: 10px; /*Set padding-top value to default's padding-top + padding-bottom */
padding-bottom: 0; /*Set padding-bottom value to 0 */
border-bottom-color: #bcbcbb; /*Highlight red color theme*/
color: black;*/
text-decoration: none;
margin: 0 1px 0 0; /*Margin between each menu item*/
padding: 5px 10px 5px 10px; /*Padding within each menu item*/
background-color: #f4f4f4; /*Default menu color*/
border-bottom: 1px solid #f4f4f4;
}

#myform{ /*CSS for sample search box. Remove if desired */
float: right;
margin: 0;
margin-top: 2px;
padding: 0;
}

#myform .textinput{
width: 190px;
border: 1px solid gray;
}

#myform .submit{
font: normal 12px Verdana;
height: 22px;
border: 1px solid #D10000;
background-color: black;
color: white;
}

</style>

<title>
  langIT
</title>
</head>
<body>
<table>
	<tr>
		<td style='background-color:#f4f4f4; height:20;vertical-align:center;padding-top:5px;border-width: 0px 0px 5px 0px; border-style:solid;border-color:#bcbcbb;'>
			<div class="container">
				<div class="span-5"><img src="<?echo KUTU_ROOT_URL;?>/common/images/logo-nlrp.gif"></div>
				<div class="span-19 last" style='margin-top:145px'><strong> Home | About Us | Programs | Activities </strong></div>
				<div class="span-24 last" style='margin-top:5px'></div>
			</div>
		</td>
	</tr>
</table>
<div class="container">
	<div class="span-24 last"><img src="<?echo KUTU_ROOT_URL;?>/common/images/content1.jpg"></div>
	<div class="span-24 last"><br><hr></div>
	<div class="span-24 last">Home | About Us | Programs | Activities<br>&nbsp;</div>
</div>
</body>
</html>