<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/lib/jquery/pagination.css" />
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.pagination.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/ui.core.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/ui.datepicker.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		//$('#menu').flickrmenu();
        $('ul.sf-menu').superfish();
	});
</script>
<hr class="space">
<h2 class="alt">Store Management</h2>
<div class="span-19">
<ul class="sf-menu">
	<li class="current">
		<a href="<?echo KUTU_ROOT_URL;?>/admin/store">Dasboard</a>
	</li>
	<li>
		<a href="<? echo KUTU_ROOT_URL;?>/admin/store/order/offset/0/limit/10/Query/">Orders</a>
	</li>
	<li>
		<a href="<? echo $this->url(array('module' => 'admin','controller'=>'store', 
						'action'=>'transaction', 'offset'=>0,'limit'=>10));?>">Transaction</a>
	</li>
	<li>
		<a href="<? echo $this->url(array('module' => 'admin','controller'=>'store', 
						'action'=>'postpaid'));?>">Postpaid Users</a>
	</li>
		<!--
    <li>
		<a href="<? echo $this->url(array('module' => 'admin','controller'=>'store', 
						'action'=>'pppayment'));?>">Postpaid Payment</a>
	</li>    
	<li>
		<a href="<? echo $this->url(array('module' => 'admin','controller'=>'store', 
						'action'=>'bpayment'));?>">Bank Payment</a>
	</li>   
		-->
	<li>
		<a href="<? echo $this->url(array('module' => 'admin','controller'=>'store', 
						'action'=>'paymentsetting'));?>">Payment Setting</a>
	</li>
	<li>
		<a href="#">More</a>
		<ul>
			<li><a href="#">Coupon</a></li>
			<li><a href="#">menu item</a></li>
			<li><a href="#">menu item</a></li>
			<li><a href="#">menu item</a></li>
			<li><a href="#">menu item</a></li>
		</ul>
	</li>	
</ul>
</div>
<br />
<br />