<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
	<title><? echo ($this->pageTitle)?($this->pageTitle):"Admin Title";?></title>

  <!-- Framework CSS -->
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/screen.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/print.css" type="text/css" media="print">
  <!--[if IE]><link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->

	
	<!-- Import fancy-type plugin for the sample page. -->
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/plugins/fancy-type/screen.css" type="text/css" media="screen, projection">
	
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/modules/admin/styles/fb-admin.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/modules/admin/styles/superfish2.css" type="text/css" media="screen, projection">
	
	<!--[if IE]><script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/js/excanvas.js"></script><![endif]-->
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.roundcorners.2.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/splitter.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.cookie.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.flickrmenu.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.validate.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/superfish.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.popupwindow.js"></script>
	
	<script type="text/javascript">
		$(document).ready(function(){
			
			$('#message_box').hide();
			//scroll the message box to the top offset of browser's scrool bar
			$(window).scroll(function()
			{
		  		$('#message_box').animate({top:$(window).scrollTop()+"px" },{queue: false, duration: 100});  
			});
		    //when the close button at right corner of the message box is clicked 
			$('#close_message').click(function()
			{
		  		//the messagebox gets scrool down with top property and gets hidden with zero opacity 
				$('#message_box').animate({ top:"+=15px",opacity:0 }, "slow");
			});
		});
	</script>

</head>

<body>
	<div id="message_box">Loading...</div>
	<div class="container">
		<div class="span-24 last" id="fb_menubar">
				<div style="padding-top:5px"></div>
				<div class="span-3" style="font-size:14px; font-weight:bold;color:white;margin-bottom:5px">
				  &nbsp;&nbsp;control panel
				</div>
				<div class="span-13">
					<div id="headerNavigation">
				  	<a href="<?echo KUTU_ROOT_URL;?>/admin/user/browse">User</a>
					<a href="<?echo KUTU_ROOT_URL;?>/admin/dms/explore">Dms</a>
					<a href="<?echo KUTU_ROOT_URL;?>/admin/acl">Access Control</a>
					<a href="<?echo KUTU_ROOT_URL;?>/admin/store">Store</a>
					<a href="<?echo KUTU_ROOT_URL;?>/admin/dms/search">Search</a>
					<a href="<?echo KUTU_ROOT_URL;?>/admin/indexing">Indexing</a>
					</div>
				</div>
				<div class="span-8 last">
					<div id="headerNavigation">
				  	<a href="<?echo KUTU_ROOT_URL;?>/admin/user/browse"><span style="font-weight:normal;"><?php echo $this->username;?></span></a>
					<a href="<?echo KUTU_ROOT_URL;?>/admin/dms/browse">My Account</a>
					<a href="<?echo KUTU_ROOT_URL;?>/identity/logout">Logout</a>
					</div>
				</div>
		</div>
		<?php echo $this->layout()->content; ?>	
	</div>
</body>
</html>