<?php
if(count($this->rowsetRelatedItem))
{
?>
	<h3>Downloadable<span class="alt"> File(s)</span></h3>
	<hr>
	<?php foreach ($this->rowsetRelatedItem as $row){?>
		<div style="padding-top:5px"></div>
		<a href="<?php echo KUTU_ROOT_URL;?>/download/<?php echo $row->itemGuid;?>"><?php echo Kutu_Core_Util::getCatalogAttributeValue($row->itemGuid, 'fixedTitle'); ?> (<?php echo Kutu_Core_Util::getCatalogAttributeValue($row->itemGuid, 'docMimeType'); ?>)</a>
		<div style="padding-top:5px"></div>
	<?php } ?>
<?php } ?>