
<?=$this->render('header.phtml');?>
<?  foreach($this->rows as $row): ?>
<fieldset class="span-20">
    <legend>Order No : <?=$this->id;?></legend>
    <div class="span-18" align="right">
    <form>
    <input type="button" value="Edit" onclick="window.location.href='<?=KUTU_ROOT_URL?>/admin/store/editOrder/id/<?=$this->id;?>'" />
    &nbsp;
    <input type="button" value="Back" onclick="javascript:history.back();" />
    &nbsp;&nbsp;&nbsp;&nbsp;
    </form>
    </div>
    <hr />
    <div class="span-4"><strong>Invoice</strong></div> <div class="span-5"><?=$row->invoiceNumber; ?>&nbsp;</div>
    <div class="span-4"><strong>USer ID</strong></div> <div class="span-5"><?=$row->userId; ?>&nbsp;</div>
    <hr />
    <div class="span-4"><strong>Tax Number</strong></div> <div class="span-5"><?=$row->taxNumber; ?>&nbsp;</div>
    <div class="span-4"><strong>Tax Company</strong></div> <div class="span-5"><?=$row->taxCompany; ?>&nbsp;</div>
    <hr />
    <div class="span-4"><strong>Tax Address</strong></div> <div class="span-5"><?=$row->taxAddress; ?>&nbsp;</div>
    <div class="span-4"><strong>tax City</strong></div> <div class="span-5"> <?=$row->taxCity; ?>&nbsp;</div>
    <hr />
    <div class="span-4"><strong>Tax ZIP</strong></div> <div class="span-5"><?=$row->taxZip; ?>&nbsp;</div>
    <div class="span-4"><strong>Tax Province</strong></div> <div class="span-5"> <?=$row->taxProvince; ?>&nbsp;</div>
    <hr />
    <div class="span-4"><strong>Tax Country</strong></div> <div class="span-5"> <?=$row->taxCountryId; ?>&nbsp;</div>
    <div class="span-4"><strong>Telephone</strong></div> <div class="span-5"> <?=$row->telephone; ?>&nbsp;</div>
    <hr />
    <div class="span-4"><strong>Payment Method</strong></div> <div class="span-5"> <?=$row->paymentMethod; ?>&nbsp;</div>
    <div class="span-4"><strong>Payment Method Note</strong></div> <div class="span-5"> <?=$row->paymentMethodNote; ?>&nbsp;</div>
    <hr />
    <div class="span-4"><strong>Last Modified</strong></div> <div class="span-5"> <?=$row->lastModified; ?>&nbsp;</div>
    <div class="span-4"><strong>Date Purchased</strong></div> <div class="span-5"> <?=$row->datePurchased; ?>&nbsp;</div>
    <hr />
    <div class="span-4"><strong>Order Status</strong></div> <div class="span-5"> <?=$row->ordersStatus; ?>&nbsp;</div>
    <div class="span-4"><strong>Date Order Finished</strong></div> <div class="span-5"> <?=$row->dateOrderFinished; ?>&nbsp;</div>
    <hr />
    <div class="span-4"><strong>Currency</strong></div> <div class="span-5"> <?=$row->currency; ?>&nbsp;</div>
    <div class="span-4"><strong>Currency Value</strong></div> <div class="span-5"> <?=$row->currencyValue; ?>&nbsp;</div>
    <hr />
    <div class="span-4"><strong>Order Total</strong></div> <div class="span-5"> <?=$row->orderTotal; ?>&nbsp;</div>
    <div class="span-4"><strong>Order Tax</strong></div> <div class="span-5"> <?=$row->orderTax ; ?>&nbsp;</div>
    <hr />
    <div class="span-4"><strong>Paypal IPN ID</strong></div> <div class="span-5"> <?=$row->paypalIpnId; ?>&nbsp;</div>
    <div class="span-4"><strong>IP Address</strong></div> <div class="span-5"> <?=$row->ipAddress; ?>&nbsp;</div>
    <hr />
    <div class="span-4"><strong>Payment Date</strong></div> <div class="span-4"><?=$row->paidDate;?>&nbsp;</div>
    <div class="span-4"><strong><input type="hidden" name="id" value="<?=$this->id;?>"></div>
</fieldset>
<? endforeach;?>
<hr />
<table>
<tr>
    <td>No</td>
    <td>Order Product ID</td>
    <td>Order ID</td>
    <td>Item ID</td>
    <td>Name</td>
    <td>Price</td>
    <td>Final Price</td>
    <td>Tax</td>
    <td>Quantity</td>
</tr>
<?$i =1; foreach($this->rowsDetail as $rowDetail): ?>
<tr>
    <td><?=$i;?></td>
    <td><?=$rowDetail['orderProductId']; ?></td>
    <td><?=$rowDetail['orderId']; ?></td>
    <td><?=$rowDetail['itemId']; ?></td>
    <td><?=$rowDetail['documentName']; ?></td>
    <td><?=$rowDetail['price']; ?></td>
    <td><?=$rowDetail['finalPrice']; ?></td>
    <td><?=$rowDetail['tax']; ?></td>
    <td><?=$rowDetail['qty']; ?></td>
</tr>
<? $i++; endforeach; ?>
</table>
<hr />