<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/lib/jquery/pagination.css
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.pagination.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		//$('#menu').flickrmenu();
        $('ul.sf-menu').superfish();
    
    var isFirstTime = 1;
	
	// First Parameter: number of items
	// Second Parameter: options object
	var myPageIndex = 0;
	var itemsPerPage = <?echo $this->itemsPerPage;?>;
	var currentOffset = <?echo $this->offset;?>;
	var limit = <?echo $this->limit;?>;
	var currentNode = "<?echo $this->currentNode;?>";
	var totalItems = <?echo $this->totalItems;?>;
	var sort = "<?echo $this->sort;?>";
	var idOrder = <? echo  $this->id; ?>;
	
	
	var tmpCurrentPageIndex = currentOffset/itemsPerPage;
	
	$("#catalogPagination").pagination(totalItems, 
	{items_per_page:itemsPerPage, callback:handlePaginationClick, current_page:tmpCurrentPageIndex}
	);
	
	function handlePaginationClick(new_page_index, pagination_container) 
	{
		if(!isFirstTime)
		{
			myPageIndex = new_page_index;
			var nextOffset = (itemsPerPage * myPageIndex);
		
			$("Offset").val(nextOffset);
			$("#frmSearch").submit();
			
			var url = "<?echo KUTU_ROOT_URL;?>/admin/store/detailOrder/id"+idOrder+"/node/"currentNode+"/offset/"+nextOffset+"/limit/"+limit+"/sort/"+sort+"/";
			window.location = url;
		}
		isFirstTime = 0;
		return false;
	}

	});
    
</script>
<?=$this->render('header.phtml');?>
<?  foreach($this->rows as $row): ?>
<table width="400px">
    <tr>
    <td colspan="2">
    Order No : <?=$this->id;?>
    </td>
    <td colspan="2"><div align="right">
    <form>
    <input type="button" value="Edit" onclick="window.location.href='<?=KUTU_ROOT_URL?>/admin/store/editOrder/id/<?=$this->id;?>'" />
    &nbsp;
    <input type="button" value="Back" onclick="javascript:history.back();" />
    &nbsp;&nbsp;&nbsp;&nbsp;
    </form>
    </div></td>
    </tr>
    <tr>
        <td>Invoice</td> <td><?=$row->invoiceNumber; ?></td>
        <td>USer ID</td> <td><?=$row->userId; ?></td>
    </tr>
    <tr>
        <td>Tax Number</td> <td><?=$row->taxNumber; ?></td>
        <td>Tax Company</td> <td><?=$row->taxCompany; ?></td>
    </tr>
    <tr>
        <td>Tax Address</td> <td><?=$row->taxAddress; ?></td>
        <td>tax City</td> <td> <?=$row->taxCity; ?></td>
    </tr>
    <tr>
        <td>Tax ZIP</td> <td><?=$row->taxZip; ?></td>
        <td>Tax Province</td> <td> <?=$row->taxProvince; ?></td>
    </tr>
    <tr>
        <td>Tax Country</td> <td> <?=$row->taxCountryId; ?></td>
        <td>Telephone</td> <td> <?=$row->telephone; ?></td>
    </tr>
    <tr>
        <td>Payment Method</td> <td> <?=$row->paymentMethod; ?></td>
        <td>Payment Method Note</td> <td> <?=$row->paymentMethodNote; ?></td>
    </tr>
    <tr>
        <td>Last Modified</td> <td> <?=$row->lastModified; ?></td>
        <td>Date Purchased</td> <td> <?=$row->datePurchased; ?></td>
    </tr>
    <tr>
        <td>Order Status</td> <td> <?=$row->orderStatus; ?></td>
        <td>Date Order Finished</td> <td> <?=$row->dateOrderFinished; ?></td>
    </tr>
    <tr>
        <td>Currency</td> <td> <?=$row->currency; ?></td>
        <td>Currency Value</td> <td> <?=$row->currencyValue; ?></td>
    </tr>
    <tr>
        <td>Order Total</td> <td> <?=$row->orderTotal; ?></td>
        <td>Order Tax</td> <td> <?=$row->orderTax ; ?></td>
    </tr>
    <tr>
        <td>Paypal IPN ID</td> <td> <?=$row->paypalIpnId; ?></td>
        <td>IP Address</td> <td> <?=$row->ipAddress; ?></td>
    </tr>
    <tr>
        <td>Payment Date</td>
        <td><?=$row->paidDate;?></td>
        <td><input type="hidden" name="id" value="<?=$this->id;?>"></td>
    </tr>
</table>
<? endforeach;?>
<hr />
<table>
<tr>
    <td>No</td>
    <td>Order Product ID</td>
    <td>Order ID</td>
    <td>Item ID</td>
    <td>Name</td>
    <td>Price</td>
    <td>Final Price</td>
    <td>Tax</td>
    <td>Quantity</td>
</tr>
<?$i =1; foreach($this->rowsDetail as $rowDetail): ?>
<tr>
    <td><?=$i;?></td>
    <td><?=$rowDetail['orderProductId']; ?></td>
    <td><?=$rowDetail['orderId']; ?></td>
    <td><?=$rowDetail['itemId']; ?></td>
    <td><?=$rowDetail['documentName']; ?></td>
    <td><?=$rowDetail['price']; ?></td>
    <td><?=$rowDetail['finalPrice']; ?></td>
    <td><?=$rowDetail['tax']; ?></td>
    <td><?=$rowDetail['qty']; ?></td>
</tr>
<? $i++; endforeach; ?>
</table>
<hr />