<?=$this->render('header.phtml');?>
<script type="text/javascript">
	$(function() {
		$("#datepicker").datepicker();
	});
	</script>
<hr class="space">
Editing data with id number<?=$this->id;?>
<p>

<form method="post">
<table width="400px">
    <tr>
        <?  foreach($this->rows as $row): ?>
        <td>Invoice</td> <td><input type="text" name="invoiceNumber" value="<?=$row->invoiceNumber; ?>" /></td>
        <td>USer ID</td> <td><input type="text" name="userId" value="<?=$row->userId; ?>"  /></td>
    </tr>
    <tr>
        <td>Tax Number</td> <td> <input type="text" name="taxNumber" value="<?=$row->taxNumber; ?>"  /></td>
        <td>Tax Company</td> <td> <input type="text" name="taxCompany" value="<?=$row->taxCompany; ?>"  /></td>
    </tr>
    <tr>
        <td>Tax Address</td> <td> <input type="text" name="taxAddress" value="<?=$row->taxAddress; ?>"  /></td>
        <td>tax City</td> <td> <input type="text" name="taxCity" value="<?=$row->taxCity; ?>" /></td>
    </tr>
    <tr>
        <td>Tax ZIP</td> <td><input type="text" name="taxZip" value="<?=$row->taxZip; ?>"  /></td>
        <td>Tax Province</td> <td> <input type="text" name="taxProvince" value="<?=$row->taxProvince; ?>"  /></td>
    </tr>
    <tr>
        <td>Tax Country</td> <td> <input type="text" name="taxCountryId" value="<?=$row->taxCountryId; ?>"  /></td>
        <td>Telephone</td> <td> <input type="text" name="telephone" value="<?=$row->telephone; ?>"  /></td>
    </tr>
    <tr>
        <td>Payment Method</td> <td> <input type="text" name="paymentMethod" value="<?=$row->paymentMethod; ?>"  /></td>
        <td>Payment Method Note</td> <td> <input type="text" name="paymentMethodNote" value="<?=$row->paymentMethodNote; ?>"  /></td>
    </tr>
    <tr>
        <td>Last Modified</td> <td> <input type="text" name="lastModified" value="<?=$row->lastModified; ?>"  /></td>
        <td>Date Purchased</td> <td> <input type="text" name="datePurchased" value="<?=$row->datePurchased; ?>"  /></td>
    </tr>
    <tr>
        <td>Order Status</td> <td> 
		<input type="hidden" name="orderaStatus" value="<?=$row->orderStatus; ?>"  />
		
		<select name="orderStatus">
		<? foreach($this->rowsStatus as $status):?>
		<option value="<?=$status['orderStatusId']?>" <? echo ($status['orderStatusId']==$row->orderStatus?'selected=selected':'') ; ?>><?=$status['ordersStatus']?>
		<? endforeach;?>
		</select>
		</td>
        <td>Date Order Finished</td> <td> <input type="text" id="datepicker" name="dateOrderFinished" value="<?=$row->dateOrderFinished; ?>"  /></td>
    </tr>
    <tr>
        <td>Currency</td> <td> <input type="text" name="currency" value="<?=$row->currency; ?>"  /></td>
        <td>Currency Value</td> <td> <input type="text" name="currencyValue" value="<?=$row->currencyValue; ?>"  /></td>
    </tr>
    <tr>
        <td>Order Total</td> <td> <input type="text" name="orderTotal" value="<?=$row->orderTotal; ?>"  /></td>
        <td>Order Tax</td> <td> <input type="text" name="orderTax" value="<?=$row->orderTax ; ?>"  /></td>
    </tr>
    <tr>
        <td>Paypal IPN ID</td> <td> <input type="text" name="paypalIpnId" value="<?=$row->paypalIpnId; ?>"  /></td>
        <td>IP Address</td> <td> <input type="text" name="ipAddress" value="<?=$row->ipAddress; ?>" /></td>
    </tr>
    <tr>
        <td>
		<input type="hidden" name="id" value="<?=$this->id;?>" />
		<input type="hidden" name="offset" value="<?=$this->offset;?>" />
		</td>
        <? endforeach;?>
    </tr>
</table>
    <input type="button" value= "back" onclick="javascript:history.back();" />
    <input type="reset" value="reset" />
    <input type="submit" name="save" value="save" />
</form>
</p>