<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/lib/jquery/pagination.css" />
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.pagination.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		//$('#menu').flickrmenu();
        $('ul.sf-menu').superfish();
    
    var isFirstTime = 1;
	
	// First Parameter: number of items
	// Second Parameter: options object
	/*
	var myPageIndex = 0;
	var itemsPerPage = <?if(empty($this->itemsPerPage)) echo 10; else echo $this->itemsPerPage;?>;
	var currentOffset = <?echo $this->offset;?>;
	var limit = <?echo $this->limit;?>;
	var currentNode = "<?echo $this->currentNode;?>";
	var totalItems = <?echo $this->totalItems;?>;
	var sort = "<?echo $this->sort;?>";
	
	
	var tmpCurrentPageIndex = currentOffset/itemsPerPage;
	
	$("#catalogPagination").pagination(totalItems, 
	{items_per_page:itemsPerPage, callback:handlePaginationClick, current_page:tmpCurrentPageIndex}
	);*/
	
	function handlePaginationClick(new_page_index, pagination_container) 
	{
		if(!isFirstTime)
		{
			myPageIndex = new_page_index;
			var nextOffset = (itemsPerPage * myPageIndex);
		
			$("Offset").val(nextOffset);
			//$("#frmSearch").submit();
			
			var url = "<?echo KUTU_ROOT_URL;?>/admin/store/index/"+currentNode+"/offset/"+nextOffset+"/limit/"+limit+"/sort/"+sort+"/";
			window.location = url;
		}
		isFirstTime = 0;
		return false;
	}

	});
    
</script>
<?=$this->render('header.phtml');?>
<?
$statusId = $this->statusId;
$status = $this->status;
$rowset = $this->rowset;
?>
<pre>
</pre>
<?
for($i=0;$i<count($status);$i++){
?>
<table>
<tr>
    <td colspan="3"><b>Status : <?=$status[$i];?>, Jumlah : <?=$this->total[$i];?></b></td>
    <td colspan="3" align="right"><div align="right">
    <a href="<? echo $this->url(array('controller'=>'store', 
            'action'=>'Order', 'status'=>$this->statusId[$i]));?>">View All <?=$status[$i];?> Orders</a>
    </div></td>
</tr>
<tr>
    <td>No</td>
    <td>Description</td>
    <td>Payment Method</td>
    <td>Order Total</td>
    <td>Total Count</td>
    <td>Action</td>
</tr>
<? for($x=0;$x<count($rowset[$i]);$x++){ ?>
<tr>
    <td><?=$x+1?></td>
    <td><?=$rowset[$i][$x]->invoiceNumber;?></td>
    <td><?=$rowset[$i][$x]->paymentMethod;?></td>
    <td><?=$rowset[$i][$x]->orderTotal;?></td>
    <td><?=$rowset[$i][$x]->countTotal;?></td>
    <td><a href="<? echo $this->url(array('controller'=>'store', 
            'action'=>'editOrder', 'id'=>$rowset[$i][$x]->orderId));?>">Edit</a>
       <a href="<? echo $this->url(array('controller'=>'store', 
            'action'=>'detailOrder', 'id'=>$rowset[$i][$x]->orderId));?>">Detail</a></td>
</tr>
<?}?>
</table>
<hr />
<hr />
<?}?>

