<link rel="stylesheet" type="text/css" media="all" href="<?echo KUTU_ROOT_URL;?>/lib/calendar/calendar-mos.css" title="green">
<script src="<?echo KUTU_ROOT_URL;?>/lib/calendar/calendar_mini.js" type="text/javascript"></script>
<script src="<?echo KUTU_ROOT_URL;?>/lib/calendar/lang/calendar-en.js" type="text/javascript"></script>
<?=$this->render('header.phtml');?>
<hr class="space">
<form id="myForm" name="myForm">
<h3>Order :</h3>
<hr class="span-20">
<?foreach($this->rowset as $row) :?>
<div class="span-5">Order ID&nbsp;</div> <div class="span-5"><?=$row->orderId; ?>&nbsp;</div>
<div class="span-5">Invoice&nbsp;</div> <div class="span-5"><?=$row->invoiceNumber; ?>&nbsp;</div>
<hr class="span-20">
<div class="span-5">USer ID&nbsp;</div> <div class="span-5"><?=$row->userId; ?>&nbsp;</div>
<div class="span-5">Tax Number&nbsp;</div> <div class="span-5"><?=$row->taxNumber; ?>&nbsp;</div>
<hr class="span-20">
<div class="span-5">Tax Company&nbsp;</div> <div class="span-5"><?=$row->taxCompany; ?>&nbsp;</div>
<div class="span-5">Tax Address&nbsp;</div> <div class="span-5"><?=$row->taxAddress; ?>&nbsp;</div>
<hr class="span-20">
<div class="span-5">tax City&nbsp;</div> <div class="span-5"> <?=$row->taxCity; ?>&nbsp;</div>
<div class="span-5">Tax ZIP&nbsp;</div> <div class="span-5"><?=$row->taxZip; ?>&nbsp;</div>
<hr class="span-20">
<div class="span-5">Tax Province&nbsp;</div> <div class="span-5"> <?=$row->taxProvince; ?>&nbsp;</div>
<div class="span-5">Tax Country&nbsp;</div> <div class="span-5"> <?=$row->taxCountryId; ?>&nbsp;</div>
<hr class="span-20">
<div class="span-5">Telephone&nbsp;</div> <div class="span-5"> <?=$row->telephone; ?>&nbsp;</div>
<div class="span-5">Payment Method&nbsp;</div> <div class="span-5"> <?=$row->paymentMethod; ?>&nbsp;</div>
<hr class="span-20">
<div class="span-5">Payment Method Note&nbsp;</div> <div class="span-5"> <?=$row->paymentMethodNote; ?>&nbsp;</div>
<div class="span-5">Last Modified&nbsp;</div> <div class="span-5"> <?=$row->lastModified; ?>&nbsp;</div>
<hr class="span-20">
<div class="span-5">Date Purchased&nbsp;</div> <div class="span-5"> <?=$row->datePurchased; ?>&nbsp;</div>
<div class="span-5">Order Status&nbsp;</div> <div class="span-5"> <?=$row->ordersStatus; ?>&nbsp;</div>
<hr class="span-20">
<div class="span-5">Date Order Finished&nbsp;</div> <div class="span-5"> <?=$row->dateOrderFinished; ?>&nbsp;</div>
<div class="span-5">Currency&nbsp;</div> <div class="span-5"> <?=$row->currency; ?>&nbsp;</div>
<hr class="span-20">
<div class="span-5">Currency Value&nbsp;</div> <div class="span-5"> <?=$row->currencyValue; ?>&nbsp;</div>
<div class="span-5">Order Total&nbsp;</div> <div class="span-5"> <?=$row->orderTotal; ?>&nbsp;</div>
<hr class="span-20">
<div class="span-5">Order Tax&nbsp;</div> <div class="span-5"> <?=$row->orderTax ; ?>&nbsp;</div>
<div class="span-5">Paypal IPN ID&nbsp;</div> <div class="span-5"> <?=$row->paypalIpnId; ?>&nbsp;</div>
<hr class="span-20">
<div class="span-5">IP Address&nbsp;</div> <div class="span-5"> <?=$row->ipAddress; ?>&nbsp;</div>
<div class="span-5">Payment Date&nbsp;</div>
<div class="span-5" id="paidDate" name="paidDate"><?=date('Y-m-d')?></div>
<input type="hidden" name="id" value="<?=$this->id;?>">
<?endforeach;?>
<hr class="span-20">
<h3>Detail :</h3>
<hr class="span-20">
<div class="span-1">No&nbsp;</div>
<div class="span-3">Product ID&nbsp;</div>
<div class="span-3">Item ID&nbsp;</div>
<div class="span-4">Name&nbsp;</div>
<div class="span-2">Price&nbsp;</div>
<div class="span-3">Final Price&nbsp;</div>
<div class="span-2">Tax&nbsp;</div>
<div class="span-2 last">Quantity&nbsp;</div>
<hr class="span-20">
<?$i =1;foreach($this->rowsetDetail as $rowDetail) :?>
<div class="span-1"><?=$i;?>&nbsp;</div>
<div class="span-3"><?=$rowDetail['orderProductId']; ?>&nbsp;</div>
<div class="span-3"><?=$rowDetail['itemId']; ?>&nbsp;</div>
<div class="span-4"><?=$rowDetail['documentName']; ?>&nbsp;</div>
<div class="span-2"><?=$rowDetail['price']; ?>&nbsp;</div>
<div class="span-3"><?=$rowDetail['finalPrice']; ?>&nbsp;</div>
<div class="span-2"><?=$rowDetail['tax']; ?>&nbsp;</div>
<div class="span-2 last"><?=$rowDetail['qty']; ?>&nbsp;</div><br/>
<hr class="span-20">
<?$i++; endforeach;?>
<hr class="span-20">
<h3>Confirmation History :</h3>
<hr class="span-23">
<div class="span-1">No</div>
<div class="span-2">Date</div>
<div class="span-3">Method</div>
<div class="span-4">Destination</div>
<div class="span-4">Sender</div>
<div class="span-3">Amount</div>
<div class="span-4">Note</div>
<div class="span-1">Extra</div>
<hr class="span-23">
<?$i=1;foreach($this->rowsetConfirm as $rowConfirm) :?>
<div class="span-1"><?=$i?></div>
<div class="span-2"><?=$rowConfirm->paymentDate;?>&nbsp;</div>
<div class="span-3"><?=$rowConfirm->paymentMethod;?>&nbsp;</div>
<div class="span-4"><?=$rowConfirm->destinationAccount;?>&nbsp;</div>
<div class="span-4">
<?=$rowConfirm->senderAccount;?><br/>
<?=$rowConfirm->senderAccountName;?><br/>
<?=$rowConfirm->bankName;?><br/>
&nbsp;</div>
<div class="span-3"><?=$rowConfirm->amount;?>&nbsp;</div>
<div class="span-4"><?=$rowConfirm->note;?>&nbsp;</div>
<?
if($rowConfirm->confirmed == 0){
	$col = "green";
	$ext = "Unconfirmed";
?>
<script>
document.getElementById('paidDate').innerHTML = '<?=$rowConfirm->paymentDate;?>';
</script>
<?
}else{
	$col = "red";
	$ext = "Rejected";
}
?>
<div class="span-1"><b><font color="<?=$col?>"><?=$ext?></font></b></div>
<hr class="span-23">
<?$i++; endforeach;?>
<div class="span-23" align="center">
<a href="<? echo $this->url(array('controller'=>'store', 
            'action'=>'payconfirmyes', 'id'=>$this->idOrder));?>">
            Accept [Confirm] </a> | 
<a href="<? echo $this->url(array('controller'=>'store', 
            'action'=>'payconfirmno', 'method'=>$row->paymentMethod, 'id'=>$this->idOrder ));?>">
            Reject </a> | 
<a href="#" onClick="javascript:history.back();">Back</a>
</div>
</form>
<hr class="span-23">

<hr class="space">
<hr class="space">
<hr class="space">
<hr class="space">





