<?=$this->render('header.phtml');?>
<hr class="space">
<fieldset class="span-16">
<legend>Add Postpaid User</legend>
<hr class="space">
<? if($this->action == 'select' ){ ?>
	Choose one user that matched with your criteria : [user contain:<?=$this->Query?>, limit to set:<?=$this->creditLimit?>]
	<div class="span-1" align="center">No</div>
	<div class="span-3" align="center">Username</div>
	<div class="span-4" align="center">Name</div>
	<div class="span-4" align="center">Company</div>
	<div class="span-3" align="center">Set Postpaid</div>
	<hr/>
	<? for($i=0;$i<count($this->userList);$i++){?>
	<div class="span-1" align="right"><?=($i+1)?></div>
		<div class="span-3"><a href="<?=KUTU_ROOT_URL?>/admin/store/postpaidadd/act/conf/id/<?=$this->userList[$i]->userId?>/CL/<?=$this->creditLimit?>/"><?=$this->userList[$i]->username?></a>&nbsp;</div>
		<div class="span-4"><?=$this->userList[$i]->firstname?> <?=$this->userList[$i]->lastname?>&nbsp;</div>
		<div class="span-4"><?=$this->userList[$i]->company?>&nbsp;</div>
		<div class="span-3" align="center"><a href="<?=KUTU_ROOT_URL?>/admin/store/postpaidadd/act/conf/id/<?=$this->userList[$i]->userId?>/CL/<?=$this->creditLimit?>/">SET</a>&nbsp;</div>
		<hr />
	<?}?>
	<input type="button" value="back" onClick="javascript:history.back()">

<?}elseif($this->action == 'conf'){?>
	<form method="post" action="<?=KUTU_ROOT_URL?>/admin/store/postpaidadd/act/done">
	<?foreach($this->rowset as $row):?>
		<div class="span-3"><strong>Username</strong></div>
		<div class="span-4"><?=$row->UN;?>&nbsp;</div>
		<div class="span-3"><strong>User ID</strong></div>
		<div class="span-4 last"><?=$row->userId;?>&nbsp;</div>
		<hr />
		<div class="span-3"><strong>Name</strong></div>
		<div class="span-4"><?=$row->FN;?> <?=$row->LN;?>&nbsp;</div>
		<div class="span-3"><strong>Username</strong></div>
		<div class="span-4 last"><?=$row->UN;?>&nbsp;</div>
		<hr />
		<div class="span-3"><strong>Tax Number</strong></div>
		<div class="span-4"><?=$row->taxNumber;?>&nbsp;</div>
		<div class="span-3"><strong>Tax Company</strong></div>
		<div class="span-4 last"><?=$row->taxCompany;?>&nbsp;</div>
		<hr />
		<div class="span-3"><strong>Tax Address</strong></div>
		<div class="span-4"><?=$row->taxAddress;?>&nbsp;</div>
		<div class="span-3"><strong>Tax city</strong></div>
		<div class="span-4 last"><?=$row->taxCity;?>&nbsp;</div>
		<hr />
		<div class="span-3"><strong>Tax Province</strong></div>
		<div class="span-4"><?=$row->taxProvince;?>&nbsp;</div>
		<div class="span-3"><strong>Tax Country ID </strong></div>
		<div class="span-4 last"><?=$row->taxCountryId;?>&nbsp;</div>
		<hr />
		<div class="span-3"><strong>Limit to Set</strong></div>
		<div class="span-4"><font color="green"><?=$this->CL;?></font>&nbsp;</div>
		<hr />
		<div align="center">
		<input type="hidden" name="id" value="<?=$row->userId;?>">
		<input type="hidden" name="CL" value="<?=$this->CL;?>">
		<input type="submit" value="Set Postpaid">
		<input type="button" value="back" onClick="javascript:history.back()">
		</div>
	<? endforeach?>
	</form>
<?}elseif($this->action == 'done'){?>
	<div class="success" align="center">
	Postpaid user succesfully added.
	</div>
<?}else{?>
	<form method="post" action="<?=KUTU_ROOT_URL?>/admin/store/postpaidadd/act/select">
		<div class="span-2">Username</div>
		<div class="span-3"><input type="text" name="username"></div>
		<hr />
		<div class="span-2">Credit Limit</div>
		<div class="span-3"><input type="text" name="creditLimit"></div>
		<hr />
		<input type="button" value="back" onClick="javascript:history.back()">
		<input type="reset">
		<input type="submit" value="add">
	</form> 
<?}?>
</fieldset>