<?=$this->render('header.phtml');?>
<hr />
<fieldset class="span-20">
<legend>Transaction</legend>
<? foreach($this->listOrder as $value): ?>
    <div class="span-4"><strong>Order ID</strong></div> <div class="span-5"><?=$value['orderId'];  ?> &nbsp;</div>
    <div class="span-4"><strong>Invoice</strong></div> <div class="span-5"><?=$value['invoiceNumber'];  ?> &nbsp;</div>
    <hr />
    <div class="span-4"><strong>User ID</strong></div> <div class="span-5"><?=$value['userId'];  ?> &nbsp;</div>
    <div class="span-4"><strong>Tax Number</strong></div> <div class="span-5"><?=$value['taxNumber'];  ?> &nbsp;</div>
    <hr />
    <div class="span-4"><strong>Tax Company</strong></div> <div class="span-5"><?=$value['taxCompany'];  ?> &nbsp;</div>
    <div class="span-4"><strong>Tax Address</strong></div> <div class="span-5"><?=$value['taxAddress'];  ?> &nbsp;</div>
    <hr />
    <div class="span-4"><strong>Tax City</strong></div> <div class="span-5"><?=$value['taxCity'];  ?> &nbsp;</div>
    <div class="span-4"><strong>Tax Zip</strong></div> <div class="span-5"><?=$value['taxZip'];  ?> &nbsp;</div>
    <hr />
    <div class="span-4"><strong>Tax Province</strong></div> <div class="span-5"><?=$value['taxProvince'];  ?> &nbsp;</div>
    <div class="span-4"><strong>Tax Country</strong></div> <div class="span-5"><?=$value['taxCountryId'];  ?> &nbsp;</div>
    <hr />
    <div class="span-4"><strong>Telephone</strong></div> <div class="span-5"><?=$value['telephone'];  ?> &nbsp;</div>
    <div class="span-4"><strong>Payment Method</strong></div> <div class="span-5"><?=$value['paymentMethod'];  ?> &nbsp;</div>
    <hr />
    <div class="span-4"><strong>Payment Menthode Note</strong></div> <div class="span-5"><?=$value['paymentMethodNote'];  ?> &nbsp;</div>
    <div class="span-4"><strong>Last Modified</strong></div> <div class="span-5">
    <?=(!empty($value['lastModified']))?strftime("%Y-%m-%d",strtotime($value['lastModified'])):'undefined'; ?> &nbsp;</div>
    <hr />
    <div class="span-4"><strong>Date Purchased</strong></div> <div class="span-5">
    <?=(!empty($value['datePurchased']))?strftime("%Y-%m-%d",strtotime($value['datePurchased'])):'undefined'; ?> &nbsp;</div>
    <div class="span-4"><strong>Order Status</strong></div> <div class="span-5"><?=$value['orderStatus'];  ?> &nbsp;</div>
    <hr />
    <div class="span-4"><strong>Date Order Finished </strong></div> <div class="span-5">
    <?=(!empty($value['dateOrderFinished']))?strftime("%Y-%m-%d",strtotime($value['dateOrderFinished'])):'undefined'; ?> &nbsp;</div>
    <div class="span-4"><strong>Currency</strong></div> <div class="span-5"><?=$value['currency'];  ?> &nbsp;</div>
    <hr />
    <div class="span-4"><strong>Currency Value</strong></div> <div class="span-5"><?=$value['currencyValue'];  ?> &nbsp;</div>
    <div class="span-4"><strong>Total Order</strong></div> <div class="span-5"><?=$value['orderTotal'];  ?> &nbsp;</div>
    <hr />
    <div class="span-4"><strong>Total Orde Tax</strong></div> <div class="span-5"><?=$value['orderTax'];  ?> &nbsp;</div>
    <div class="span-4"><strong>Paypal IPN ID</strong></div> <div class="span-5"><?=$value['paypalIpnId'];  ?> &nbsp;</div>
    <hr />
    <div class="span-4"><strong>IP Address</strong></div> <div class="span-5"><?=$value['ipAddress'];  ?> &nbsp;</div>
    <div class="span-4"><strong>Payment Date</strong></div> <div class="span-5">
    <?=(!empty($value['paidDate']))?strftime("%Y-%m-%d",strtotime($value['paidDate'])):'undefined'; ?>  &nbsp;</div>
    
<? endforeach;  ?>
</fieldset>
<hr />
<fieldset>
<legend>Detail</legend>
    <strong>
    <div class="span-1" align="center">No</div>
    <div class="span-3" align="center">Item ID</div>
    <div class="span-5" align="center">Name</div>
    <div class="span-2" align="center">Price</div>
    <div class="span-2" align="center">Final Price</div>
    <div class="span-2" align="center">Tax</div>
    <div class="span-1 last" align="center">Quantity</div>
    </strong>
<hr />
<? $i=1; foreach($this->listOrderDetail as $valueDetail): ?>
<div class="span-1"><?=$i?>&nbsp;</div>
<div class="span-3"><?=$valueDetail['itemId']; ?> &nbsp;</div>
<div class="span-5"><?=$valueDetail['documentName']; ?> &nbsp;</div>
<div class="span-2" align="right"><?=number_format($valueDetail['price'],2); ?> &nbsp;</div>
<div class="span-2" align="right"><?=number_format($valueDetail['finalPrice'],2); ?> &nbsp;</div>
<div class="span-2" align="right"><?=number_format($valueDetail['tax'],2); ?> %&nbsp;</div>
<div class="span-1" align="center"><?=$valueDetail['qty']; ?> &nbsp;</div>
<hr />
<?  $i++; endforeach;  ?>
</fieldset>
<hr />
<fieldset>
<legend>Payment History</legend>
<div class="span-1">No.&nbsp;</div>
<div class="span-3">Date&nbsp;</div>
<div class="span-3">Status&nbsp;</div>
<div class="span-4">Note&nbsp;</div>
<hr />
<? $i=1; foreach($this->rowsetHistory as $valueHistory): ?>
<div class="span-1" align="right"><?=$i?>&nbsp;</div>
<div class="span-3"><?=strftime("%Y-%m-%d",strtotime($valueHistory['dateCreated'])); ?> &nbsp;</div>
<div class="span-3"><?=$valueHistory['ordersStatus']; ?> &nbsp;</div>
<div class="span-4"><?=$valueHistory['note']; ?> &nbsp;</div>
<hr />
<?  $i++; endforeach;  ?>
</fieldset>
<fieldset>
<legend>Paypal Payment History</legend>
<strong>
<div class="span-2">No.&nbsp;</div>
<div class="span-3">Date&nbsp;</div>
<div class="span-3">Status&nbsp;</div>
</strong>
<hr />
<? $i=1; foreach($this->rowsetPaypalHistory as $valuePaypalHistory): ?>
<div class="span-2"><?=$i?>&nbsp;</div>
<div class="span-3"><?=strftime("%Y-%m-%d", strtotime($valuePaypalHistory['dateAdded'])); ?> &nbsp;</div>
<div class="span-3"><?=$valuePaypalHistory['paymentStatus']; ?> &nbsp;</div>
<hr />
<?  $i++; endforeach;  ?>
</fieldset>