<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Sample Page</title>

  <!-- Framework CSS -->
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/screen.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/print.css" type="text/css" media="print">
  <!--[if IE]><link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->

	
	<!-- Import fancy-type plugin for the sample page. -->
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/plugins/fancy-type/screen.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/modules/site/styles/site.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/modules/site/styles/superfish.css" type="text/css" media="screen, projection">

	<!--[if IE]><script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/js/excanvas.js"></script><![endif]-->
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.roundcorners.2.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/splitter.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.cookie.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.flickrmenu.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.validate.js"></script>
	<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/superfish.js"></script>
	
	<script type="text/javascript">
		$(document).ready(function(){
			
		});
	</script>
	<script type="text/javascript">
		$(document).ready(function(){
			 $('ul.sf-menu').superfish();


		});
	</script>

</head>

<body>
	<div class="container">
	
		<div class="span-10 prepend-14 last" style="background:#0a67a0">
			<div style="padding-top:5px"></div>
			<?if(empty($this->username)){?>
					<a href="<?echo KUTU_ROOT_URL;?>" style="font-color:#fff">/identity/login">Login/Sign up</a> |
				<?}
				else { echo "Hello, ". $this->username;?>
					 <a href="<?echo KUTU_ROOT_URL;?>/identity/logout" style="color:#fff">Logout</a> |
					<a href="<?echo KUTU_ROOT_URL;?>/site/myaccount" style="color:#fff">My Account</a> |
					<a href="<?echo KUTU_ROOT_URL;?>/site/store/checkout" style="color:#fff">View Cart</a> |
				<?}?>
				<a href="#" style="color:#fff">Help</a> | <a href="#" style="color:#fff">Contact Us</a>
				<div style="padding-top:5px"></div>
		</div>
		<div class="span-24"  style="background:#1b5088">
				&nbsp;<br>
				<div class="span-12 prepend-1">
				  <!--<h1>LGS Online</h1>-->
					<h2 style="color:#fff;">Lubis Gani Surowidjojo</h2>
				</div>

				

				<div class="span-10 last">
					<div class="span-2">
						<span style="font-size:14px">&nbsp;</span>
					</div>
					<div class="span-8 last">
						<form id="frmSearch" name="frmSearch" action="<?echo KUTU_ROOT_URL;?>/site/dms/search" method="GET">
							<input id="sQuery" name="sQuery" size=30 value='<?echo $this->sQuery;?>'>
							<input type="hidden" id="sLimit" name="sLimit" value="10">
							<input type="hidden" id="sOffset" name="sOffset" value="<?echo $this->sOffset;?>">
							<input type="submit" id="btnGoSearch" value="Search">
						</form>
					</div>
				</div>
			
		</div>
		 
		
		<!--<div class="darker"></div>-->
		<div class="span-24 prepend-3">
			<!--<a href="<?echo KUTU_ROOT_URL;?>/site">Home</a> |
				<?if(empty($this->username)){?> 
					<a href="<?echo KUTU_ROOT_URL;?>/site/index/about">Lgs Legal Database</a> 
				<?}
				else { //echo "Hello, ". $this->username;?>
					 <a href="<?echo KUTU_ROOT_URL;?>/dms">Lgs Legal Database</a>
				<?}?>
				| <a href="#">News & Opportunities</a> | <a href="#">LGS Profile</a>
				| <a href="#">Lgs Awards</a> | <a href="#">LGS Profile</a>
				| <a href="#">Testimonies</a> | <a href="#">LGS Clients</a> -->
				<ul class="sf-menu">
					<li class="current">
						<a href="<?echo KUTU_ROOT_URL;?>/site">Home</a>
					</li>
					<li>
						<?if(empty($this->username)){?> 
							<a href="<?echo KUTU_ROOT_URL;?>/site/index/about">Lgs Legal Database</a> 
						<?}
						else { //echo "Hello, ". $this->username;?>
							 <a href="<?echo KUTU_ROOT_URL;?>/dms">Lgs Legal Database</a>
						<?}?>
					</li>
					<li>
						<a href="#">News & Opportunities</a>
					</li>
					<li>
						<a href="#">LGS Profile</a>
					</li>	
					<li>
						<a href="#">Lgs Awards</a>
					</li>
					<li>
						<a href="#">Testimonies</a>
					</li>
					<li>
						<a href="#">LGS Clients</a>
						<!--<ul>
							<li><a href="#">menu item</a></li>
							<li><a href="#">menu item</a></li>
							<li><a href="#">menu item</a></li>
							<li><a href="#">menu item</a></li>
							<li><a href="#">menu item</a></li>
						</ul>-->
					</li>
					<li>
						<a href="#">&nbsp;</a>
					</li>
				</ul>
		</div>
		<div class="lighter"></div>
		
		<?php echo $this->layout()->content; ?>
		
		<div class="span-3 prepend-21"><IMG src="<?echo KUTU_ROOT_URL;?>/common/images/logo-iso2.jpg" /></div>	
	</div>
</body>
</html>