<!--
design by styleshout(http://www.styleshout.com/)
adapted to SilveStripe by SilverStriped (http://silverstriped.com)
-->
<!--<xml version="1.0" encoding="UTF-8">-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >

  <head>
		<base href="http://www.nlrp.org/" />
		<title>Program strategies and outcomes</title>
<meta name="generator" http-equiv="generator" content="SilverStripe 2.3.0 - http://www.silverstripe.com" />
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Language" content="en"/>

		<link rel="shortcut icon" href="/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="<?echo KUTU_ROOT_URL;?>/common/modules/nlrp/css/layout.css" />
<link rel="stylesheet" type="text/css" href="<?echo KUTU_ROOT_URL;?>/common/modules/nlrp/css/typography.css" />
<link rel="stylesheet" type="text/css" href="<?echo KUTU_ROOT_URL;?>/common/modules/nlrp/css/form.css" />
</head>
<body>
<div id="wrap">
	<div id="top-bg"></div>
	<!--<div id="header">			
				
		<h1 id="logo-text"><a href="index.html" title="">NLRP<span>National Legal Reform Program</span></a></h1>		
		<p id="slogan">put your site slogan here...</p>		
			
		<div id="header-links">
		<p>
			<a href="index.html">Home</a> | 
			<a href="index.html">Contact</a> | 
			<a href="index.html">Site Map</a>			
		</p>		
		</div>						
	</div>-->
		
	<div id="header-photo"></div>		

	<div  id="nav">
		<ul>
 		  
  	<li><a href="<?echo KUTU_ROOT_URL;?>/pages/m/home" title="Go to the Home page" class="link"><span>Home</span></a></li>
  	  
  	<li><a href="<?echo KUTU_ROOT_URL;?>/pages/g/lgs4a1bb86c12807/h/1" title="Go to the About Us page" class="link"><span>About Us</span></a></li>
  	  
  	<li><a href="http://localhost/kutump-enhanced/pages/g/lgs4a0eee8fbe5bf/h/1" title="Go to the Programs page" class="section"><span>Programs</span></a></li>
  	  
  	<li><a href="/media-room/" title="Go to the Media Room page" class="link"><span>Media Room</span></a></li>
  	  
  	<li><a href="/procurement/" title="Go to the Procurement page" class="link"><span>Procurement</span></a></li>
  	  
  	<li><a href="/partnerships/" title="Go to the Partnerships page" class="link"><span>Partnerships</span></a></li>
  	  
  	<li><a href="/links/" title="Go to the Links page" class="link"><span>Links</span></a></li>
  
</ul>
	</div>					
	<div id="content-wrap">
	
		<div id="mainHome">		
			<?php echo $this->layout()->content; ?>
			


			
						
			<br />	

		</div>
				
				
			
	</div>
		
	<div id="footer-wrap">
		<div id="footer-columns">
	
			<div class="col3">
				<h3>Our Programs</h3>
				<ul>
					<li><a href="http://www.nlrp.org/programs/">Enhanced Planning through Management and Budgetary Reform</a></li>
					<li><a href="http://www.nlrp.org/programs/">Enhanced Public Accountability through National Surveys and Assessments</a></li>
					<li><a href="http://www.nlrp.org/programs/">Enhanced Professionalism through Capacity Building, Career Planning and Training</a></li>
					<li><a href="http://www.nlrp.org/programs/">Enhanced Legal Certainty through Legal Information</a></li>
					<li><a href="http://www.nlrp.org/programs/">Enhanced Integrity and Transparency through Anti-Corruption Initiatives</a></li>
				</ul>
			</div>

			<div class="col3-center">&nbsp;</div>
			<!--<div class="col3-center">
				<h3>Sed purus</h3>
				<ul>
					<li><a href="index.html">consequat molestie</a></li>
					<li><a href="index.html">sem justo</a></li>
					<li><a href="index.html">semper</a></li>
					<li><a href="index.html">magna sed purus</a></li>
					<li><a href="index.html">tincidunt</a></li>
				</ul>
			</div>-->

			<div class="col3">
				<h3>News</h3>
				<ul>
					<li><a href="index.html">consequat molestie</a></li>
					<li><a href="index.html">sem justo</a></li>
					<li><a href="index.html">semper</a></li>
					<li><a href="index.html">magna sed purus</a></li>
					<li><a href="index.html">tincidunt</a></li>					
				</ul>
			</div>

		</div>	
	
		<div id="footer-bottom">		
			
			<p>
			&copy; 2009 <strong>NLRP - National Legal Reform Project</strong> <!--| 
			Adapted by: <a href="http://www.silverstriped.com/">SilverStriped</a> |
			Powered by: <a href="http://www.silverstripe.com/">SilverStripe open source CMS</a> |-->
</p>		
			
		</div>	

<!-- footer ends-->
</div>
<!-- wrap ends here -->
</div>

</body>
</html>