<ul class="sf-menu">
	<li class="current">
		<a href="<?echo KUTU_ROOT_URL;?>/pages">Home</a>
	</li>
	<li>
		<?if(empty($this->username)){?> 
			<a href="<?echo KUTU_ROOT_URL;?>/pages/g/lgs4a1d7b209f3df">LGS Legal Database</a> 
		<?}
		else { //echo "Hello, ". $this->username;?>
			 <a href="<?echo KUTU_ROOT_URL;?>/dms">Lgs Legal Database</a>
		<?}?>
	</li>
	<li>
		<a href="<?echo KUTU_ROOT_URL;?>/pages/g/lgs4a1d77eb99e7a">News & Opportunities</a>
	</li>
	<li>
		<a href="<?echo KUTU_ROOT_URL;?>/pages/g/lgs4a1d79ad94802">LGS Profile</a>
		<?echo $this->action('getmenuchildren','component','site',array('node'=>'lgs4a1d79ad94802'))?>
	</li>	
	<li>
		<a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d84f8ab672">What Others Say About LGS</a>
	</li>
	<li>
		<a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d79809737a">LGS News</a>
		
	</li>
	<li>
		<a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d783104616">LGS Newsletters</a>
		
	</li>
	<li>
		<a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d8484cd013">LGS Awards</a>
		
	</li>
	<li>
		<a href="#">More &nbsp;&nbsp;&nbsp;&nbsp;</a>
		<ul>
			<li><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d79d321b76">Message from the Board</a></li>
			<li><a href="<?echo KUTU_ROOT_URL;?>/pages/g/lgs4a1d7937a6f9b">Indonesia Under Review</a></li>
			<li><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d7a02e32c1">Who's Who in Indonesia</a></li>
			<li><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d7a32b3755">Important Addresses</a></li>
			<li><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d7b8f71285">Important Public Documents And Articles</a></li>
			<li><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d7b68b6227">Q & A With LGS Partners</a></li>
		</ul>
	</li>
</ul>