<?php $guid = $this->generateGuid();?>
<div id="<?php echo $guid;?>spinner" style="color:red; display:none;"><img src="<?php echo $this->getKutuRootUrl();?>/app/resources/images/wait-trans.gif" border="0"> Sending Request</div>
<?php foreach ($this->rowsetFolder as $row){?>
	<div style="padding-top:5px"></div>
	<a href="<?php echo KUTU_ROOT_URL;?>/admin/dms/explore/node/<?php echo $row->guid;?>"><?php echo $row->title; ?></a>
	<?php if($this->isAllowed($this->catalogGuid, 'update','content')){?>
	- <a href="#" onclick="<?php echo $guid;?>removeFromFolder('<?php echo $this->catalogGuid;?>', '<?php echo $row->guid;?>');return false;">Remove</a>
	<?php }?>
	<div style="padding-top:5px"></div>
<?php } ?>
<script type="text/javascript">
function <?php echo $guid;?>removeFromFolder(catalogGuid, folderGuid)
{
	if(confirm ('Are you sure to remove this?'))
	{
		window.location = "<?echo KUTU_ROOT_URL;?>/admin/dms_catalog/removefromfolder/guid/"+catalogGuid+"/folderGuid/"+folderGuid;
		
	}
}
</script>