<?php $guid = $this->generateGuid();?>
<div id="legalbasis-page">
<table width="100%" cellpadding="0" cellspacing="0">
	<tr>
		<td>
			<div style="padding:0px;">
				<?php foreach ($this->aData as $data){?>
					
					<?if($data['node']==$this->catalogGuid) {?>
					<?php } else {?>
						<a href="<?echo KUTU_ROOT_URL;?>/admin/dms_catalog/details/guid/<?php echo $data['node'];?>"><?php echo $data['title']; ?></a>
						<?php if($this->isAllowed($this->catalogGuid, 'update','content')){?>
						- <a href="javascript:;" onclick="<?php echo $guid;?>remove('<?php echo $data['nodeLeft'];?>', '<?php echo $data['nodeRight'];?>', 'RELATED_TRANSLATION');return false;">Remove</a>
						<!--<br><strong>Catatan: </strong><?php echo $data['description']; ?>-->
						<?php }?>
						<br><?php echo $data['subTitle']; ?>
						<div style="padding-top:5px"></div>
					<?}?>
					
				<?php }?>
			</div>
		</td>
	</tr>
</table>
</div>
<script type="text/javascript">
function <?php echo $guid;?>remove(itemGuid, relatedGuid, relateAs)
{
	if(confirm ('Are you sure to remove this?'))
	{
		window.location = "<?echo KUTU_ROOT_URL;?>/admin/dms_relation/remove/guid/"+itemGuid+"/relatedGuid/"+relatedGuid+"/relateAs/"+relateAs;
		
	}
}
</script>