<br>
LGS ONLINE now offers you the ability to set up a LGS ONLINE Websignal on your Blackbery. Once you have registered for the LGS ONLINE Websignal service, an icon will appear on your BlackBerry desktop. Whenever there is a breaking news story from LGS ONLINE, the icon's appearance will change color. To view the breaking news story, click the icon. When there is no breaking news story, the icon will act as a bookmark and provide easy access to the LGS ONLINE Rich Mobile Site.
<br>
To register for the LGS ONLINE BlackBerry Websignal service, enter an email address that you can access on your BlackBerry below and click the "Send" button. We will send you an email that contains an embedded URL. Using your BlackBerry, open the email, click on the URL and follow the instructions to confirm your registration for the LGS ONLINE BlackBerry Websignal service.
<br>
&nbsp;