<h3>My <span class="alt">Dashboard</span></h3>
<a href="<? echo KUTU_ROOT_URL;?>/site/myaccount">Dashboard</a>
<hr class="space"><hr class="space">
<h3>Manage <span class="alt">Profile</span></h3>
<a href="<? echo KUTU_ROOT_URL;?>/site/myaccount/editprofile">Edit Profile</a>
<div style="padding-top:10px"></div>
<a href="<? echo KUTU_ROOT_URL;?>/site/myaccount/changepassword">Change Password</a>
<div style="padding-top:10px"></div>
<a href="<? echo KUTU_ROOT_URL;?>/site/myaccount/changeemail">Change Email Address</a>
<hr class="space"><hr class="space">

<h3>Reports <span class="alt"></span> </h3>
<a href="#">Order History</a>
<div style="padding-top:10px"></div>
<a href="#">Transaction History</a>
<hr class="space"><hr class="space">

<h3>My <span class="alt">Documents</span> </h3>
<a href="#">View All</a>
<hr class="space"><hr class="space">	

<h3>Others <span class="alt"></span> </h3>
<a href="#">Newsletter</a>
<div style="padding-top:10px"></div>
<a href="#">Blackberry Notification</a>
<hr class="space"><hr class="space">