<!--<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.js"></script>-->
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.selectboxes.js"></script>
<link rel="stylesheet" type="text/css" href="<?echo KUTU_ROOT_URL;?>/lib/jquery/jstree/tree_component.css" />

<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jstree/_lib/css.js"></script>

<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jstree/tree_component.js"></script>
<style type="text/css">
<!--
// -->
</style>
<script type="text/javascript">
$(document).ready(function() {
	//$('ul.sf-menu').superfish();
	
	$("#demo21").tree({
	  data  : {
	    type  : "json",
	    json  : [ 
	      { attributes: { id : "pjson_1" }, state: "open", data: "Root node 1", children : [
	        { attributes: { id : "pjson_2" }, data: "custom icon" },
	        { attributes: { id : "pjson_3" }, data: "Child node 2" },
	        { attributes: { id : "pjson_4" }, data: "Some other child node" }
	      ]}, 
	      { attributes: { id : "pjson_5" }, data: "Root node 2" },
	 		
	    ]
	   	
	  },
	ui : {
	    theme_name : "checkbox"
	  },
	callback    : {
				
				onselect    : function(NODE,TREE_OBJ) { 
							alert(TREE_OBJ.selected.text);
							$("#targetNode").val(TREE_OBJ.selected.attr("id"));
					}
			
			}
	
	});
	
	$("#demo2").tree({
	      data  : {
	        type  : "json", // or "xml_nested" or "xml_nested"
	        url   : "<?echo KUTU_ROOT_URL;?>/admin/dms_folder/getchildreninjson",
	        async : true,
	        async_data : function (NODE) { return { id : $(NODE).attr("id") || 0, my_param : "my_value" } }
	      },
		callback    : {

					onselect    : function(NODE,TREE_OBJ) { 
								//alert(TREE_OBJ.selected.text());
								$("#targetNodeTitle").val(TREE_OBJ.selected.text());
								$("#targetNode").val(TREE_OBJ.selected.attr("id"));
						}

				},
			cookies : { prefix : "treeCategories", opts : { path : '/' }}
	    });
	
	var currentNode = "<?echo $this->backToNode;?>";
	
	var message = "<?echo $this->message;?>";
	if(message!="")
	{
		alert (message);
	}
	$("#lkSetAsRoot").click(function()
	{
		$("#targetNodeTitle").val("ROOT");
		$("#targetNode").val('root');
		//$("#frmMoveFolder").submit();
	} );

});
</script>
<hr class="space">
<h2 class="alt">Folder Management: Move Folder</h2>
<ul class="sf-menu">
	<li class="current">
		<a href="<?echo KUTU_ROOT_URL;?>/admin/dms/explore/node/<?echo $this->backToNode;?>">Back to Folder</a>
	</li>	
</ul>
<div class="span-12 colborder">
	<hr class="space">
	You will move the following folders:
	<br>
	<strong><?echo $this->folderTitle;?></strong>
	<br>To:
	<br>
	<form class="" id="frmMoveFolder" method="post" action="">
		<fieldset>
			<legend>Selected Target Folder</legend>
			<p>
				<label for="targetNode">Target Folder</label>
				<input type="text" id="targetNodeTitle" name="targetNodeTitle" value="">
				<input type="hidden" id="targetNode" name="targetNode" value="">
				<input type="hidden" id="guid" name="guid" value="<?echo $this->guid;?>">
				<input type="hidden" id="backToNode" name="backToNode" value="<?echo $this->backToNode;?>">
			</p>
			<p>
				<label for="Save">&nbsp;</label>
				<input class="submit" type="submit" value="Save"/> &nbsp; <a href="#" id="lkSetAsRoot">Set as ROOT</a>
			</p>
		</fieldset>
	</form>
</div>
<div class="span-11 last">
	<h3>Choose Folders</h3>
	<div id="demo2" class="demo"></div>
</div>
<div class="span-24">
	
	
	
</div>