<!--
design by styleshout(http://www.styleshout.com/)
adapted to SilveStripe by SilverStriped (http://silverstriped.com)
-->
<!--<xml version="1.0" encoding="UTF-8">-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >

  <head>
		<base href="http://www.nlrp.org/" />
		<title><?echo $this->pageTitle;?></title>
<meta name="generator" http-equiv="generator" content="SilverStripe 2.3.0 - http://www.silverstripe.com" />
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Language" content="en"/>

	<!-- Framework CSS -->
		<!--<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/screen.css" type="text/css" media="screen, projection">
		<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/print.css" type="text/css" media="print">-->
		<link rel="stylesheet" type="text/css" href="<?echo KUTU_ROOT_URL;?>/common/modules/nlrp/css/blueprint.css" />
	  <!--[if IE]><link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->

		<link rel="shortcut icon" href="/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="<?echo KUTU_ROOT_URL;?>/common/modules/nlrp/css/layout.css" />
<link rel="stylesheet" type="text/css" href="<?echo KUTU_ROOT_URL;?>/common/modules/nlrp/css/typography.css" />
<link rel="stylesheet" type="text/css" href="<?echo KUTU_ROOT_URL;?>/common/modules/nlrp/css/form.css" />
<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/modules/nlrp/css/superfish.css" type="text/css" media="screen, projection">

<!--[if IE]><script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/js/excanvas.js"></script><![endif]-->
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.roundcorners.2.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/splitter.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.cookie.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.flickrmenu.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.validate.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/superfish.js"></script>

<script type="text/javascript">
	$(document).ready(function(){
		
	});
</script>
<script type="text/javascript">
	$(document).ready(function(){
		 $('ul.sf-menu').superfish();


	});
</script>
</head>
<body>
<div id="wrap">
	<div id="top-bg"></div>
	<!--<div id="header">			
				
		<h1 id="logo-text"><a href="index.html" title="">NLRP<span>National Legal Reform Program</span></a></h1>		
		<p id="slogan">put your site slogan here...</p>		
			
		<div id="header-links">
		<p>
			<a href="index.html">Home</a> | 
			<a href="index.html">Contact</a> | 
			<a href="index.html">Site Map</a>			
		</p>		
		</div>						
	</div>-->
		
	<div id="header-photo"></div>

	<div  id="nav">
		<?echo $this->action('mainmenu','pages_component','sitenlrp')?>
		<!--<ul class="sf-menu">
			<li class="">
				<a href="<?echo KUTU_ROOT_URL;?>/pages">Home</a>
			</li>

			<li>
				<a href="<?echo KUTU_ROOT_URL;?>/pages/g/lgs4a1bb86c12807/h/1">About Us</a>
				<?echo $this->sMenuAboutUs;?>
			</li>
			<li>
				<a href="#">Programs</a>
				<?echo $this->sMenuPrograms;?>
			</li>	
			<li>
				<a href="<?echo KUTU_ROOT_URL;?>/pages/g/nlrp4a1c354d26b45/h/1">Media Room</a>
				<?echo $this->sMenuMediaRoom;?>
			</li>
			<li>
				<a href="#">Procurement</a>
			</li>
			<li>
				<a href="#">Partnerships</a>
				<ul>
					<li><a href="#">menu item</a></li>
					<li><a href="#">menu item</a></li>
					<li><a href="#">menu item</a></li>
					<li><a href="#">menu item</a></li>
					<li><a href="#">menu item</a></li>
				</ul>
			</li>
			<li>
				<a href="#">Links</a>
			</li>
		</ul>-->
	</div>			
	<div id="content-wrap">
			
		<?php echo $this->layout()->content; ?>

							
	</div>
		
	<?=$this->render("pages/footer.phtml")?>
<!-- wrap ends here -->
</div>

</body>
</html>