<!--
design by styleshout(http://www.styleshout.com/)
adapted to SilveStripe by SilverStriped (http://silverstriped.com)
-->
<!--<xml version="1.0" encoding="UTF-8">-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >

  <head>
		<base href="http://www.nlrp.org/" />
		<title>Program strategies and outcomes</title>
<meta name="generator" http-equiv="generator" content="SilverStripe 2.3.0 - http://www.silverstripe.com" />
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Language" content="en"/>

	<!-- Framework CSS -->
		<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/screen.css" type="text/css" media="screen, projection">
		<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/print.css" type="text/css" media="print">
	  <!--[if IE]><link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/styles/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->

		<link rel="shortcut icon" href="/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="<?echo KUTU_ROOT_URL;?>/common/modules/nlrp/css/layout.css" />
<link rel="stylesheet" type="text/css" href="<?echo KUTU_ROOT_URL;?>/common/modules/nlrp/css/typography.css" />
<link rel="stylesheet" type="text/css" href="<?echo KUTU_ROOT_URL;?>/common/modules/nlrp/css/form.css" />
<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/common/modules/nlrp/css/superfish.css" type="text/css" media="screen, projection">

<!--[if IE]><script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/js/excanvas.js"></script><![endif]-->
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.roundcorners.2.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/splitter.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.cookie.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.flickrmenu.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.validate.js"></script>
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/superfish.js"></script>

<script type="text/javascript">
	$(document).ready(function(){
		
	});
</script>
<script type="text/javascript">
	$(document).ready(function(){
		 $('ul.sf-menu').superfish();


	});
</script>
</head>
<body>
<div id="wrap">
	<div id="top-bg"></div>
	<!--<div id="header">			
				
		<h1 id="logo-text"><a href="index.html" title="">NLRP<span>National Legal Reform Program</span></a></h1>		
		<p id="slogan">put your site slogan here...</p>		
			
		<div id="header-links">
		<p>
			<a href="index.html">Home</a> | 
			<a href="index.html">Contact</a> | 
			<a href="index.html">Site Map</a>			
		</p>		
		</div>						
	</div>-->
		
	<div id="header-photo"></div>

	<div  id="nav">
		<ul class="sf-menu">
			<li class="">
				<a href="<?echo KUTU_ROOT_URL;?>/pages">Home</a>
			</li>

			<li>
				<a href="<?echo KUTU_ROOT_URL;?>/pages/g/lgs4a1bb86c12807/h/1">About Us</a>
				<?echo $this->sMenuAboutUs;?>
			</li>
			<li>
				<a href="#">Programs</a>
				<?echo $this->sMenuPrograms;?>
			</li>	
			<li>
				<a href="<?echo KUTU_ROOT_URL;?>/pages/g/nlrp4a1c354d26b45/h/1">Media Room</a>
				<?echo $this->sMenuMediaRoom;?>
			</li>
			<li>
				<a href="#">Procurement</a>
			</li>
			<li>
				<a href="#">Partnerships</a>
				<ul>
					<li><a href="#">menu item</a></li>
					<li><a href="#">menu item</a></li>
					<li><a href="#">menu item</a></li>
					<li><a href="#">menu item</a></li>
					<li><a href="#">menu item</a></li>
				</ul>
			</li>
			<li>
				<a href="#">Links</a>
			</li>
		</ul>
	</div>
						
	<div id="content-wrap">
	
		<div id="main">		
			<?php echo $this->layout()->content; ?>
			


			
						
			<br />	

		</div>
				
		<div id="sidebar">
			





<!--<h3>Sidebar Menu</h3>-->
		<ul class="sidemenu">	
		  
			<li><a href="/enhanced-planning-through-management-and-budgetary-reform/" title="Go to the Enhanced Planning through Management and Budgetary Reform page" class="section"><strong>Enhanced Planning through Management and Budgetary Reform</strong></a>
			 
				 
		         <ul class="subsub"> 
		          
		            <li><a href="/program-strategies-and-outcomes/" title="ADV: Program strategies and outcomes page" class="current">Program strategies and outcomes</a></li> 
		          
		            <li><a href="/output-and-implementation/" title="ADV: Output and Implementation page" class="link">Output and Implementation</a></li> 
		          
		            <li><a href="/indicators-and-planned-activities/" title="ADV: Indicators and Planned Activities page" class="link">Indicators and Planned Activities</a></li> 
		          
		            <li><a href="/news-1/" title="ADV: News page" class="link">News</a></li> 
		          
		            <li><a href="/publication-research-and-studies/" title="ADV: Publication, Research and Studies page" class="link">Publication, Research and Studies</a></li> 
		          
		         </ul><!--.subsub--> </li>
		         
			
		  
			<li><a href="/enhanced-public-accountability-through-national-surveys-and-assessments/" title="Go to the Enhanced Public Accountability through National Surveys and Assessments page" class="link"><strong>Enhanced Public Accountability through National Surveys and Assessments</strong></a>
			
		  
		</ul>







	


		</div>		
			
	</div>
		
	<div id="footer-wrap">
		<div id="footer-columns">
	
			<div class="col3">
				<h3>Our Programs</h3>
				<ul>
					<li><a href="http://www.nlrp.org/programs/">Enhanced Planning through Management and Budgetary Reform</a></li>
					<li><a href="http://www.nlrp.org/programs/">Enhanced Public Accountability through National Surveys and Assessments</a></li>
					<li><a href="http://www.nlrp.org/programs/">Enhanced Professionalism through Capacity Building, Career Planning and Training</a></li>
					<li><a href="http://www.nlrp.org/programs/">Enhanced Legal Certainty through Legal Information</a></li>
					<li><a href="http://www.nlrp.org/programs/">Enhanced Integrity and Transparency through Anti-Corruption Initiatives</a></li>
				</ul>
			</div>

			<div class="col3-center">&nbsp;</div>
			<!--<div class="col3-center">
				<h3>Sed purus</h3>
				<ul>
					<li><a href="index.html">consequat molestie</a></li>
					<li><a href="index.html">sem justo</a></li>
					<li><a href="index.html">semper</a></li>
					<li><a href="index.html">magna sed purus</a></li>
					<li><a href="index.html">tincidunt</a></li>
				</ul>
			</div>-->

			<div class="col3">
				<h3>News</h3>
				<ul>
					<li><a href="index.html">consequat molestie</a></li>
					<li><a href="index.html">sem justo</a></li>
					<li><a href="index.html">semper</a></li>
					<li><a href="index.html">magna sed purus</a></li>
					<li><a href="index.html">tincidunt</a></li>					
				</ul>
			</div>

		</div>	
	
		<div id="footer-bottom">		
			
			<p>
			&copy; 2009 <strong>NLRP - National Legal Reform Project</strong> <!--| 
			Adapted by: <a href="http://www.silverstriped.com/">SilverStriped</a> |
			Powered by: <a href="http://www.silverstripe.com/">SilverStripe open source CMS</a> |-->
</p>		
			
		</div>	

<!-- footer ends-->
</div>
<!-- wrap ends here -->
</div>

</body>
</html>