<div class="span-35 prepend-1 append-1 last">
<h2 class="alt">Edit Billing Info</h2>
<hr>
<div class="span-35 prepend-1 append-1 last">
	<a href="<? echo KUTU_ROOT_URL;?>/site/myaccount">My Account</a> || 
	<!-- <input type="button" value= "My Account" onclick="javascript:history.back();" /> -->
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/list">Order </a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/transaction">Transaction </a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/confirm">Confirmation</a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/billing">Billing Info</a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/document">Documents</a>
</div>
<div class="span-14 last" align="right">

</div>

<hr>
<fieldset class="span-15">
<legend>Edit Info</legend>
<form method="post">
<? 
foreach($this->rowset as $row) :
?>
<input type="hidden" name="userId" value="<?=$row->userId; ?>" >
<input type="hidden" name="createdDate" value="<?=$row->createdDate; ?>" >
<input type="hidden" name="createdBy" value="<?=$row->createdBy; ?>" >
<input type="hidden" name="modifiedDate" value="<?=$row->modifiedDate; ?>" >
<input type="hidden" name="modifiedBy" value="<?=$row->modifiedBy; ?>" >

<div class="span-5"><strong>Tax Number</strong></div>
<div class="span-6"><input type="text" name="taxNumber" value="<?=$row->taxNumber; ?>" ></div>
<hr class="space"> 

<div class="span-5"><strong>Tax Company</strong></div>
<div class="span-6"><input type="text" name="taxCompany" value="<?=$row->taxCompany; ?>" ></div> 
<hr class="space">

<div class="span-5"><strong>Tax Address</strong></div>
<div class="span-6"><textarea name="taxAddress"><?=$row->taxAddress; ?></textarea></div> 
<hr class="space">

<div class="span-5"><strong>Tax City</strong></div>
<div class="span-6"><input type="text" name="taxCity" value="<?=$row->taxCity; ?>" ></div> 
<hr class="space">

<div class="span-5"><strong>Tax Province</strong></div>
<div class="span-6"><input type="text" name="taxProvince" value="<?=$row->taxProvince; ?>" ></div> 
<hr class="space">

<div class="span-5"><strong>Tax ZIP</strong></div>
<div class="span-6"><input type="text" name="taxZip" value="<?=$row->taxZip; ?>" ></div> 
<hr class="space">

<div class="span-5"><strong>Tax Country ID</strong></div>
<div class="span-5"><input type="text" name="taxCountryId" value="<?=$row->taxCountryId; ?>" ></div>
<hr class="space">
<hr />
<?
$remain =  ($row->creditLimit) - ($this->outstandingAmount);
$limit = '<div class="span-5"><strong>Limit</strong></div><div class="span-6">'
		.$row->creditLimit.'</div><hr class="space"><div class="span-5">
		<strong>Otstanding Amount</strong></div><div class="span-5">'
		.$this->outstandingAmount.'</div><hr class="space">
		<div class="span-5"><strong>Limit Remain</strong></div>
		<div class="span-5">'.$remain.'</div><hr />';
($row->isPostPaid == 1)?$value=$limit:$value='';
?>
<?=$value?>
<?endforeach;?>
<div class="span-12">
<input type="reset" value="reset">
<input type="submit" name="save" value="save">
</div>
</form>
</fieldset>
</div>