<title>Canceled</title></head><body><h3></h3>
<div class="span-24">
<fieldset><legend>Order Canceled</legend>
<h3>The order was canceled.</h3><hr class="space">
Your order with paypal payment has been succesfully canceled, now you can continue to <a href="<?=KUTU_ROOT_URL?>/site/store/checkout">pay with other method</a> or just continue <a href="<?=KUTU_ROOT_URL?>/dms">browsing our database</a>.
</fieldset>
</div>
