<div class="span-35 prepend-1 append-1 last">
<h2 class="alt">Payment Confirmation</h2>
<?if(!empty($this->sended)):?>
<div class="span-23 success" align="center"><h3><?=$this->sended?></h3></div>
<?endif;?>
<hr>
<div class="span-35 prepend-1 append-1 last">
	<a href="<? echo KUTU_ROOT_URL;?>/site/myaccount">My Account</a> || 
	<!-- <input type="button" value= "My Account" onclick="javascript:history.back();" /> -->
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/list">Order </a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/transaction">Transaction </a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/confirm">Confirmation</a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/billing">Billing Info</a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/document">Documents</a>
</div>
<div class="span-14 last" align="right">
<!--<form id="frmSearch" name="frmSearch" method="GET" action="<?=KUTU_ROOT_URL;?>/site/store_payment/search">
	<input id="sQuery" name="sQuery" size=30 value='<?echo $this->sQuery;?>'> 
	<input type="hidden" id="sLimit" name="sLimit" value="10">
	<input type="hidden" id="sOffset" name="sOffset" value="<?echo $this->sOffset;?>">
	<input type="submit" id="btnGoSearch" value="Search">
</form>
-->
</div>
<script src="<?echo KUTU_ROOT_URL;?>/lib/calendar.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" media="all" href="<?echo KUTU_ROOT_URL;?>/lib/calendar/calendar-mos.css" title="green">
<script src="<?echo KUTU_ROOT_URL;?>/lib/calendar/calendar_mini.js" type="text/javascript"></script>
<script src="<?echo KUTU_ROOT_URL;?>/lib/calendar/lang/calendar-en.js" type="text/javascript"></script>
<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/lib/jquery/pagination.css" />
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.pagination.js"></script>
<script>
	function showResults() {
		 var resultMsg1=0
		 var resultMsg2=0
		 var invdiv ='';
		 <?
		 foreach($this->rowset as $value){
			$arr1[] = $value['orderTotal'];
			$arr2[] = $value['currencyValue'];
			$inv[]  = $value['orderId'].'/'.$value['orderTotal'].'/'.$value['countTotal'];
		 }
		 ?>
		<? for($i=0;$i<count($arr1);$i++){?>
		 
		 if(document.payconfirm.orderId[<? echo $i?>].checked){ 
		 resultMsg1+=parseFloat(<? echo ($arr1[$i])?>)
		 resultMsg2+=parseFloat(<? echo ($arr2[$i]*$arr1[$i])?>)
		 invdiv+="<? echo $inv[$i]?>\n"
		 }
		<?}?>
		 document.getElementById('amountid').innerHTML=resultMsg2		 
		 document.getElementById('amountus').innerHTML=resultMsg1		 
		 document.getElementById('invoicex').innerHTML=invdiv		 
		 //alert(resultMsg1+'*'+resultMsg3+'='+resultMsg2);
	}
</script>
<hr class="space">
<fieldset>
<legend><?=$this->numCount;?> data(s) of unconfirmed payment.</legend>
<hr>
<form name="payconfirm" id="payconfirm" method="post" action="payconfirm">
	<strong>
    <div class="span-1" align="center">No&nbsp;</div>
    <div class="span-4" align="center">Invoice&nbsp;</div>
    <div class="span-4" align="center">date Purchased&nbsp;</div>
    <!-- <div class="span-4">Payment Date&nbsp;</div> -->
    <div class="span-2" align="center">Total Price&nbsp;</div>
    <div class="span-1" align="center">Qty&nbsp;</div>
    <div class="span-2" align="center">Method&nbsp;</div>
    <div class="span-3" align="center">Status&nbsp;</div>
    <div class="span-1 last" align="center">Pay&nbsp;</div>
	</strong>
<hr />
<? $i = $this->offset + 1; ?>
<? if(!empty($_POST['searchid'])):?>
    <?=header('Location: '.$this->url(array('controller'=>'store_payment', 
            'action'=>'detail', 'id'=>$_POST['searchid'])));?>
<? endif; ?>
<? foreach($this->rowset as $value): ?>
<? if($value['orderStatus'] == 3 or $value['orderStatus'] == 5){
	$anchor = 'trdetail';
	}else{
	$anchor = 'detail';
	}
	if($value['orderStatus']==4){
		$color = "green";
	}elseif($value['orderStatus']==6){
		$color = "orange";
	}else{
		$color = "black";
	}
?>	
	<font color="<?=$color?>">
    <div class="span-1" align="right"><a href="<?=$this->url(array('controller'=>'store_payment', 'action'=>$anchor, 'id'=>$value['orderId'])); ?>"><?=$i;?></a>&nbsp;</div>
    <div class="span-4"><a href="<?=$this->url(array('controller'=>'store_payment', 
        'action'=>$anchor, 'id'=>$value['orderId'])); ?>"><?=$value['invoiceNumber']; ?></a>&nbsp;</div>
    <div class="span-4" align="center"><?=strftime("%Y-%m-%d", strtotime($value['datePurchased'])); ?>&nbsp;</div>
    <!-- <div class="span-4"><?=$value['dateOrderFinished']; ?>&nbsp;</div> -->
    <div class="span-2" id="orderTotale" align="right"><?=$value['orderTotal']; ?>&nbsp;</div>
    <div class="span-1" align="right"><?=$value['countTotal']; ?>&nbsp;</div>
    <div class="span-2"><?=$value['paymentMethod']; ?>&nbsp;</div>
    <div class="span-3"><?=$value['ordersStatus']; ?>&nbsp;</div>
    <div class="span-1 last">
	<?if(($value['orderStatus']==4) ){?>
	<input type="checkbox" id="orderId" name="orderId[<?=$i?>]" disabled="disabled">
	<?}else{?>
	<input type="checkbox" id="orderId" name="orderId[<?=$i?>]" value="<?=$value['orderId']?>" onClick="showResults();">
	<?}?>
	&nbsp;</div>
    <hr />
	</font>
<? $i++; endforeach;  ?>
</fieldset>
<hr/>
<fieldset class="span-16">
    <div class="span-15">
	<div class="span-5"><strong>Order ID/Total/Qty</strong></div>
    <div class="span-7 last"><textarea id="invoicex" name="invoicex">&nbsp;</textarea></div>
    <div class="span-5"><strong>Payment Method</strong></div>
	<div class="span-7 last">
        <select name="paymentMethod">
            <option value="atm transfer">ATM Transfer
            <option value="cash bank">Cash Bank
            <option value="transfer">Transfer
            <option value="internet banking">Internet Banking
        </select>
    </div>
<hr>
    <div class="span-5"><strong>Bank Account Destination</strong></div>
    <div class="span-7 last">
    <select name="destinationAccount">
        <? foreach($this->bankAccount as $destAccount){
            $acc = explode("|", $destAccount->settingValue);
        }
        foreach($acc as $accN ){
        ?>
        <option value="<?=$accN?>"><?=$accN?>
        <?}?>
    </select>
    </div>
<hr>
    <div class="span-5"><strong>Date</strong></div>
    <div class="span-7 last">
    <input type="text" name="paymentDate" id="paymentDate" value="<?=date('Y-m-d')?>"><input class="button" type="reset" value="..." onclick="return showCalendar('paymentDate');" name="cmddprebiddate"/></div>
<hr>
    <div class="span-5"><strong>Amount</strong></div>
    <div class="span-7 last">
	<input class="span-1" type="radio" name="currency" value="IDR"><strong>IDR :</strong> <div class="span-1" name="amountid" id="amountid">0</div><hr class="space" />
	<input class="span-1" type="radio" name="currency" checked="checked" value="USD"><strong>USD :</strong> <div class="span-1" name="amountus" id="amountus">0</div>
	</div>
<hr>
    <div class="span-5"><strong>Sender Account</strong></div>
    <div class="span-7 last"><input type="text" name="senderAccount"></div>
<hr>
    <div class="span-5"><strong>Sender Account Name</strong></div>
    <div class="span-7 last"><input type="text" name="senderAccountName"></div>
<hr>
    <div class="span-5"><strong>Bank Name</strong></div>
    <div class="span-7 last"><input type="text" name="bankName"></div>
<hr>
    <div class="span-5"><strong>Notes</strong></div>
    <div class="span-7 last"><textarea name="note"></textarea></div>
<hr>
    <div class="span-8"><input type="submit" value="Confirm Payment"/></div>
</div>
</fieldset>
</form>

<table width='100%'>
	<tr>
		<td width=35%>&nbsp;</td>
		<td align=right><div id='catalogPagination' class="pagination">&nbsp;</div></td>
	</tr>
</table>
</div>