<div class="span-35 prepend-1 append-1 last">
<h2 class="alt">Order Detail</h2>
<hr>
<div class="span-17">
	<a href="<? echo KUTU_ROOT_URL;?>/site/myaccount">My Account</a> || 
	<!-- <input type="button" value= "My Account" onclick="javascript:history.back();" /> -->
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/list">Order </a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/transaction">Transaction </a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/confirm">Confirmation</a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/billing">Billing Info</a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/document">Documents</a>
</div>
<hr />
<fieldset><legend>ORDER </legend>
<? foreach($this->listOrder as $value): ?>
 <div class="span-5"><strong>OrderID </strong> </div><div class="span-6"> <?=$value['orderId'];  ?> &nbsp; </div>
    <div class="span-5 last"><strong>Invoice </strong></div><div class="span-6"> <?=$value['invoiceNumber'];  ?> &nbsp; </div>
<hr />

    <div class="span-5"><strong>User ID </strong></div><div class="span-6"> <?=$value['userId'];  ?> &nbsp; </div>
    <div class="span-5 last"><strong>Tax Number </strong></div><div class="span-6"> <?=$value['taxNumber'];  ?> &nbsp; </div>
<hr />

    <div class="span-5"><strong>Tax Company </strong></div><div class="span-6"> <?=$value['taxCompany'];  ?> &nbsp; </div>
    <div class="span-5 last"><strong>Tax Address </strong></div><div class="span-6"> <?=$value['taxAddress'];  ?> &nbsp; </div>
<hr />

    <div class="span-5"><strong>Tax City </strong></div><div class="span-6"> <?=$value['taxCity'];  ?> &nbsp; </div>
    <div class="span-5 last"><strong>Tax Zip </strong></div><div class="span-6"> <?=$value['taxZip'];  ?> &nbsp; </div>
<hr />

    <div class="span-5"><strong>Tax Province </strong></div><div class="span-6"> <?=$value['taxProvince'];  ?> &nbsp; </div>
    <div class="span-5 last"><strong>Tax Country </strong></div><div class="span-6"> <?=$value['taxCountryId'];  ?> &nbsp; </div>
<hr />

    <div class="span-5"><strong>Telephone </strong></div><div class="span-6"> <?=$value['telephone'];  ?> &nbsp; </div>
    <div class="span-5 last"><strong>Payment Method </strong></div><div class="span-6"><?=$value['paymentMethod'];  ?> &nbsp; </div>
<hr />

    <div class="span-5"><strong>Payment Menthode Note</strong> </div><div class="span-6"> <?=$value['paymentMethodNote'];  ?> &nbsp; </div>
    <div class="span-5 last"><strong>Last Modified </strong></div><div class="span-6"> <?=(!empty($value['lastModified']))?strftime("%Y-%m-%d", strtotime($value['lastModified'])):'undefined';  ?> &nbsp; </div>
<hr />
    <div class="span-5"><strong>Date Purchased </strong></div><div class="span-6"> <?=(!empty($value['datePurchased']))?strftime("%Y-%m-%d", strtotime($value['datePurchased'])):"Undefined";  ?> &nbsp; </div>
    <div class="span-5 last"><strong>Order Status </strong></div><div class="span-6"> <?=$value['ordersStatus'];  ?> &nbsp; </div>
<hr />
    <div class="span-5"><strong>Date Order Finished </strong></div><div class="span-6"><?
	if(empty($value['dateOrderFinished'])){
		echo 'Undefined';
	}else{
		echo strftime("%Y-%m-%d", strtotime($value['dateOrderFinished']));
	}?> &nbsp; </div>
    <div class="span-5 last"><strong>Currency </strong></div><div class="span-6"> <?=$value['currency'];  ?> &nbsp; </div>
<hr />
    <div class="span-5"><strong>Currency Value </strong></div><div class="span-6"> <?=$value['currencyValue'];  ?> &nbsp; </div>
    <div class="span-5 last"><strong>Total Order </strong></div><div class="span-6"> <?=$value['orderTotal'];  ?> &nbsp; </div>
<hr />
    <div class="span-5"><strong>Total Orde Tax </strong></div><div class="span-6"> <?=$value['orderTax'];  ?> &nbsp; </div>
    <div class="span-5 last"><strong>Paypal IPN ID </strong></div><div class="span-6"> <?=$value['paypalIpnId'];  ?> &nbsp; </div>
<hr />
    <div class="span-5"><strong>IP Address </strong></div><div class="span-6"> <?=$value['ipAddress'];  ?> &nbsp; </div>
<hr />
<? endforeach;  ?>
</fieldset>
<hr />
<fieldset>
<legend>DETAIL</legend>
<hr />
<strong>
<div class="span-1" align="center">No.</div>
<div class="span-4" align="center">Item ID</div>
<div class="span-4" align="center">Item Name</div>
<div class="span-2" align="center">Price</div>
<div class="span-2" align="center">Final Price</div>
<div class="span-2" align="center">Tax (%)</div>
<div class="span-2" align="center">Quantity</div>
</strong>
<hr />
<? $i=1; foreach($this->listOrderDetail as $valueDetail): ?>
<div class="span-1" align="right"><?=$i?></div>
<div class="span-4"><?=$valueDetail['itemId']; ?> </div>
<div class="span-4"><?=$valueDetail['documentName']; ?> </div>
<div class="span-2"align="right"><?=number_format($valueDetail['price'],2); ?> </div>
<div class="span-2"align="right"><?=number_format($valueDetail['finalPrice'],2); ?> </div>
<div class="span-2"align="right"><?=number_format($valueDetail['tax'],2); ?> </div>
<div class="span-2"align="right"><?=number_format($valueDetail['qty'],2); ?> </div>
<hr />
<?  $i++; endforeach;  ?>
</fieldset>
</div>