<h2 class="alt">Order Detail</h2>
<hr>
<div class="span-17">
	<a href="<? echo KUTU_ROOT_URL;?>/site/myaccount">My Account</a> || 
	<!-- <input type="button" value= "My Account" onclick="javascript:history.back();" /> -->
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/order">Order History</a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/transaction">Transaction History</a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/billing">Edit Billing Info</a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/document">Documents</a>
</div>
<hr />
ORDER : 
<? foreach($this->listOrder as $value): ?>
    <div class="span-11">Order ID : <?=$value['orderId'];  ?> </div>
    <div class="span-11 last">Invoice : <?=$value['invoiceNumber'];  ?> </div>

    <div class="span-11">User ID : <?=$value['userId'];  ?> </div>
    <div class="span-11 last">Tax Number : <?=$value['taxNumber'];  ?> </div>

    <div class="span-11">Tax Company : <?=$value['taxCompany'];  ?> </div>
    <div class="span-11">Tax Address : <?=$value['taxAddress'];  ?> </div>

    <div class="span-11">Tax City : <?=$value['taxCity'];  ?> </div>
    <div class="span-11">Tax Zip : <?=$value['taxZip'];  ?> </div>

    <div class="span-11">Tax Province : <?=$value['taxProvince'];  ?> </div>
    <div class="span-11">Tax Country : <?=$value['taxCountryId'];  ?> </div>

    <div class="span-11">Telephone : <?=$value['telephone'];  ?> </div>

    <div class="span-11">Payment Method :<?=$value['paymentMethod'];  ?> </div>
    <div class="span-11">Payment Menthode Note : <?=$value['paymentMethodNote'];  ?> </div>

    <div class="span-11">Last Modified : <?=$value['lastModified'];  ?> </div>
    <div class="span-11">Date Purchased : <?=$value['datePurchased'];  ?> </div>

    <div class="span-11">Order Status : <?=$value['orderStatus'];  ?> </div>
    <div class="span-11">Date Order Finished :<?=$value['dateOrderFinished'];  ?> </div>

    <div class="span-11">Currency : <?=$value['currency'];  ?> </div>
    <div class="span-11">Currency Value : <?=$value['currencyValue'];  ?> </div>

    <div class="span-11">Total Order : <?=$value['orderTotal'];  ?> </div>
    <div class="span-11">Total Orde Tax : <?=$value['orderTax'];  ?> </div>

    <div class="span-11">Paypal IPN ID : <?=$value['paypalIpnId'];  ?> </div>
    <div class="span-11">IP Address : <?=$value['ipAddress'];  ?> </div>
<? endforeach;  ?>
<hr />
DETAIL : 
<table width="200" border="1">
  <tr>
    <td>No.</td>
    <td>Product ID</td>
    <td>Order ID</td>
    <td>Item ID</td>
    <td>Item Name</td>
    <td>Price</td>
    <td>Final Price</td>
    <td>Tax</td>
    <td>Quantity</td>
  </tr>
<? $i=1; foreach($this->listOrderDetail as $valueDetail): ?>
<tr>
<td><?=$i?></td>
<td><?=$valueDetail['orderProductId']; ?> </td>
<td><?=$valueDetail['orderId']; ?> </td>
<td><?=$valueDetail['itemId']; ?> </td>
<td><?=$valueDetail['documentName']; ?> </td>
<td><?=number_format($valueDetail['price'],2); ?> </td>
<td><?=number_format($valueDetail['finalPrice'],2); ?> </td>
<td><?=number_format($valueDetail['tax'],2); ?> </td>
<td><?=number_format($valueDetail['qty'],2); ?> </td>
</tr>
<?  $i++; endforeach;  ?>
</table>
