<div class="span-35 prepend-1 append-1 last">
<h2 class="alt">Documents</h2>
<hr>
<div class="span-17 prepend-1 append-1 last">
	<a href="<? echo KUTU_ROOT_URL;?>/site/myaccount">My Account</a> || 
	<!-- <input type="button" value= "My Account" onclick="javascript:history.back();" /> -->
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/list">Order </a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/transaction">Transaction </a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/confirm">Confirmation</a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/billing">Billing Info</a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/document">Documents</a>
</div>
<div class="span-16 last" align="right">
<form id="frmSearch" name="frmSearch" method="GET">
	<input id="Query" name="Query" size=30 value='<?echo $this->Query;?>'> 
	<input type="hidden" id="limit" name="limit" value="10">
	<input type="hidden" id="offset" name="offset" value="<?echo $this->offset;?>">
	<input type="submit" id="btnGoSearch" name="btnGoSearch" value="Search">
</form>
</div>
<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/lib/jquery/pagination.css" />
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.pagination.js"></script>
<script>
$(document).ready(function(){
	
	var isFirstTime = 1;
	
	// First Parameter: number of items
	// Second Parameter: options object
	var myPageIndex = 0;
	var itemsPerPage = <?echo $this->itemsPerPage;?>;
	var currentOffset = <?echo $this->offset;?>;
	var limit = <?echo $this->limit;?>;
	var currentNode = "<?echo $this->currentNode;?>";
	var totalItems = <?echo $this->numCount;?>;
	var sort = "<?echo $this->sort;?>";
	
	
	var tmpCurrentPageIndex = currentOffset/itemsPerPage;
	
	$("#catalogPagination").pagination(totalItems, 
	{items_per_page:itemsPerPage, callback:handlePaginationClick, current_page:tmpCurrentPageIndex}
	);
	
	function handlePaginationClick(new_page_index, pagination_container) 
	{
		if(!isFirstTime)
		{
			myPageIndex = new_page_index;
			var nextOffset = (itemsPerPage * myPageIndex);
		
			$("#offset").val(nextOffset);
			//$("#frmSearch").submit();
			
			var url = "<?echo KUTU_ROOT_URL;?>/site/store_payment/document"+currentNode+"/offset/"+nextOffset+"/limit/"+limit+"/sort/"+sort+"/";
			window.location = url;
		}
		isFirstTime = 0;
		return false;
	}
	
	
});
</script>
<b>Data number <?=($this->offset+1>$this->numCount)?$this->numCount:$this->offset+1; ?> to <?=($this->offset+$this->limit>$this->numCount)?$this->numCount:$this->offset+$this->limit>$this->numCount; ?> from <?=$this->numCount;?> data(s)</b>
<hr>
<strong>
<div class="span-1" align="center">No.</div>
<!--
<div class="span-3">Product ID</div>
<div class="span-4">Order ID</div>
<div class="span-4">Item ID</div>
-->
<div class="span-4" align="center">Purchasing Date</div>
<div class="span-8" align="center">Item Name</div>
<div class="span-2 last" align="center">Download</div>
</strong>
<hr />
<? $i=$this->offset + 1; foreach($this->rowset as $valueDetail): ?>
<div class="span-1 prepend" align="right"><?=$i?></div>
<!--
<div class="span-3"><?=$valueDetail['orderProductId']; ?> </div>
<div class="span-4"><?=$valueDetail['orderId']; ?> </div>
<div class="span-4"><?=$valueDetail['itemId']; ?> </div>
-->
<div class="span-4" align="center"><?=strftime("%Y-%m-%d", strtotime($valueDetail['purchasingDate'])); ?>&nbsp </div>
<div class="span-8"><?=$valueDetail['documentName']; ?>&nbsp </div>
<div class="span-2 last"><a href="<?=KUTU_ROOT_URL;?>/pages/g/<?=$valueDetail['itemId']; ?>" title="click here to download this document">download</a> </div>
<hr />
<?  $i++; endforeach;  ?>
<table width='100%'>
	<tr>
		<td width=35%>&nbsp;</td>
		<td align=right><div id='catalogPagination' class="pagination">&nbsp;</div></td>
	</tr>
</table>
</div>