<div class="span-35 prepend-1 append-1 last">
<h2 class="alt">Order History</h2>
<hr>
<div class="span-17 prepend-1 append-1 last">
	<a href="<? echo KUTU_ROOT_URL;?>/site/myaccount">My Account</a> || 
	<!-- <input type="button" value= "My Account" onclick="javascript:history.back();" /> -->
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/list">Order </a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/transaction">Transaction </a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/confirm">Confirmation</a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/billing">Billing Info</a> || 
	<a href="<? echo KUTU_ROOT_URL;?>/site/store_payment/document">Documents</a>
</div>
<div class="span-16 last" align="right">
<form id="frmSearch" name="frmSearch" method="POST" >
	<input id="Query" name="Query" size=30 value="<?echo $this->Query;?>"> 
	<input type="hidden" id="Limit" name="Limit" value="10">
	<input type="hidden" id="Offset" name="Offset" value="<?echo $this->Offset;?>">
	<input type="submit" id="btnGoSearch" value="Search">
</form>
</div>
<link rel="stylesheet" href="<?echo KUTU_ROOT_URL;?>/lib/jquery/pagination.css" />
<script type="text/javascript" src="<?echo KUTU_ROOT_URL;?>/lib/jquery/jquery.pagination.js"></script>
<script>
$(document).ready(function(){
	
	var isFirstTime = 1;
	
	// First Parameter: number of items
	// Second Parameter: options object
	var myPageIndex = 0;
	var itemsPerPage = <?echo $this->itemsPerPage;?>;
	var currentOffset = <?echo $this->offset;?>;
	var limit = <?echo $this->limit;?>;
	var currentNode = "<?echo $this->currentNode;?>";
	var totalItems = <?echo $this->numCount;?>;
	var sort = "<?echo $this->sort;?>";
	
	
	var tmpCurrentPageIndex = currentOffset/itemsPerPage;
	
	$("#catalogPagination").pagination(totalItems, 
	{items_per_page:itemsPerPage, callback:handlePaginationClick, current_page:tmpCurrentPageIndex}
	);
	
	function handlePaginationClick(new_page_index, pagination_container) 
	{
		if(!isFirstTime)
		{
			myPageIndex = new_page_index;
			var nextOffset = (itemsPerPage * myPageIndex);
		
			$("#sOffset").val(nextOffset);
			//$("#frmSearch").submit();
			
			var url = "<?echo KUTU_ROOT_URL;?>/site/store_payment/list"+currentNode+"/offset/"+nextOffset+"/limit/"+limit+"/Query/<?echo $this->Query;?>/sort/"+sort+"/";
			window.location = url;
		}
		isFirstTime = 0;
		return false;
	}
	
	
});
</script>
<b>Data number <?=($this->offset+1>$this->numCount)?$this->numCount:$this->offset+1; ?> to <?=($this->offset+$this->limit>$this->numCount)?$this->numCount:$this->offset+$this->limit>$this->numCount; ?> from <?=$this->numCount;?> data(s)</b>
<hr>
	<strong>
    <div class="span-1" align="center">No&nbsp;</div>
    <div class="span-2" align="center">Order ID&nbsp;</div>
    <div class="span-3" align="center">Invoice&nbsp;</div>
    <div class="span-4" align="center">date Purchased&nbsp;</div>
    <!-- <div class="span-4">Payment Date&nbsp;</div> -->
    <div class="span-2" align="center">Total Price&nbsp;</div>
    <div class="span-1" align="center">Qty&nbsp;</div>
    <div class="span-2" align="center">Method&nbsp;</div>
    <div class="span-3" align="center">Status&nbsp;</div>
    <div class="span-3 last" align="center">Action&nbsp;</div>
	</strong>
<hr />
<? $i = $this->offset + 1; ?>
<? if(!empty($_POST['searchid'])):?>
    <?=header('Location: '.$this->url(array('controller'=>'store_payment', 
            'action'=>'detail', 'id'=>$_POST['searchid'])));?>
<? endif; ?>
<? foreach($this->listOrder as $value): ?>
<? if($value['orderStatus'] == 3 or $value['orderStatus'] == 5){
	$anchor = 'trdetail';
	}else{
	$anchor = 'detail';
	}
?>
    <div class="span-1" align="right"><a href="<?=$this->url(array('controller'=>'store_payment', 
        'action'=>$anchor, 'id'=>$value['orderId'])); ?>"><?=$i;?></a>&nbsp;</div>
	<div class="span-2" align="right"><a href="<?=$this->url(array('controller'=>'store_payment', 
        'action'=>$anchor, 'id'=>$value['orderId'])); ?>"><?=$value['orderId'];?></a>&nbsp;</div>
    <div class="span-3"><a href="<?=$this->url(array('controller'=>'store_payment', 
        'action'=>$anchor, 'id'=>$value['orderId'])); ?>"><?=$value['invoiceNumber']; ?></a>&nbsp;</div>
    <div class="span-4" align="center"><?=strftime("%Y-%m-%d", strtotime($value['datePurchased'])); ?>&nbsp;</div>
    <!-- <div class="span-4"><?=$value['dateOrderFinished']; ?>&nbsp;</div> -->
    <div class="span-2" align="right"><?=$value['orderTotal']; ?>&nbsp;</div>
    <div class="span-1" align="center"><?=$value['countTotal']; ?>&nbsp;</div>
    <div class="span-2"><?=$value['paymentMethod']; ?>&nbsp;</div>
    <div class="span-3"><?=$value['ordersStatus']; ?>&nbsp;</div>
    <div class="span-3 last">
	<? if($value['orderStatus']==1){
	?>
	<form method="post" action="<?=KUTU_ROOT_URL?>/site/store/paymentselected">
	<input type="hidden" name="pending" value="yes">
	<input type="hidden" name="orderId" value="<?=$value['orderId']?>">
	<input type="submit" value="pay with paypal">
	</form>
	<?
	}
	?>
	&nbsp;</div>
    <hr />
<? $i++; endforeach;  ?>
<table width='100%'>
	<tr>
		<td width=35%>&nbsp;</td>
		<td align=right><div id='catalogPagination' class="pagination">&nbsp;</div></td>
	</tr>
</table>
</div>